<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Olivia Cattau">
<meta name="author" content="Steven B. Roberts">
<meta name="dcterms.date" content="2023-01-01">
<meta name="description" content="Annotation of five geoduck RNA-seq libraries and comparative analysis against Venerida clam genomes to identify tissue-specific and candidate reproductive genes.">

<title>Comparative Genomic Analysis of Geoduck Clam (Panopea generosa) – Current Findings</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/logo.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f3a7e4420bdcbdb5f5332fa4f27636c7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/logo.svg" alt="Current Findings logo" class="navbar-logo light-content">
    <img src="../../assets/logo.svg" alt="Current Findings logo" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Current Findings</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../reports.html"> 
<span class="menu-text">Reports</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/RobertsLab/current-findings"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">1</span> Abstract</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background"><span class="header-section-number">2</span> Background</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">3</span> Methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">5</span> Discussion</a></li>
  <li><a href="#data-and-code-availability" id="toc-data-and-code-availability" class="nav-link" data-scroll-target="#data-and-code-availability"><span class="header-section-number">6</span> Data and code availability</a></li>
  <li><a href="#suggested-citation" id="toc-suggested-citation" class="nav-link" data-scroll-target="#suggested-citation"><span class="header-section-number">7</span> Suggested citation</a></li>
  <li><a href="#version-history" id="toc-version-history" class="nav-link" data-scroll-target="#version-history"><span class="header-section-number">8</span> Version history</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">9</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Comparative Genomic Analysis of Geoduck Clam (Panopea generosa)</h1>
<p class="subtitle lead">A short non-peer-reviewed scientific report</p>
  <div class="quarto-categories">
    <div class="quarto-category">genomics</div>
    <div class="quarto-category">transcriptomics</div>
    <div class="quarto-category">comparative-genomics</div>
    <div class="quarto-category">reproduction</div>
    <div class="quarto-category">geoduck</div>
    <div class="quarto-category">aquaculture</div>
  </div>
  </div>

<div>
  <div class="description">
    Annotation of five geoduck RNA-seq libraries and comparative analysis against Venerida clam genomes to identify tissue-specific and candidate reproductive genes.
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Olivia Cattau </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Washington
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Steven B. Roberts </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Washington
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2023</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">June 17, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Status
</div>
</div>
<div class="callout-body-container callout-body">
<p>This report is a Roberts Lab working manuscript. It has not been peer reviewed.</p>
<p>It is shared to make small scientific efforts, preliminary analyses, technical observations, and exploratory work openly available.</p>
<p>This report corresponds to Chapter 2 of Olivia Cattau’s M.S. thesis, <em>Developing Tools and Resources for Maturation Control in Bivalvia</em> (University of Washington, 2023).</p>
</div>
</div>
<section id="abstract" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="abstract"><span class="header-section-number">1</span> Abstract</h2>
<p>Pacific geoduck (<em>Panopea generosa</em>) is a subtidal clam species with a range from Alaska to Baja California. In this study, five transcriptomic libraries from three tissue types (gonad, heart, ctenidia) and two different life stages (larvae, juvenile) were assembled and annotated with biological ontological information. A particular emphasis in this study were reproductive genes and the gonad library, as the most likely location for reproductive candidate genes for gene editing. In addition, a comparative genomic approach was used to look for homologous genes across the Venerida clade. This effort represents an establishment of an important genomic resource for Pacific geoduck that will be valuable in the improvement of sustainable aquaculture.</p>
</section>
<section id="background" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="background"><span class="header-section-number">2</span> Background</h2>
<p>Farming of geoduck clams, <em>Panopea generosa</em>, in the cold, nutrient-rich, and clean waters of the Pacific Northwest is a long-standing tradition and important cultural, economic, and ecological part of the coastal communities <span class="citation" data-cites="feldman2004comprehensive">(<a href="#ref-feldman2004comprehensive" role="doc-biblioref">Feldman et al. 2004</a>)</span>. Geoduck clams live deep in the intertidal zone (-2.0 feet and below) but have been observed as deep as 360 feet <span class="citation" data-cites="wdfw2023geoduck">(<a href="#ref-wdfw2023geoduck" role="doc-biblioref">WDFW 2023</a>)</span>. Geoduck clams are large, long-lived, and fecund. They are reproductive as males as early as 2 years old and are often considered market size at 5 years old. In the wild, geoducks are found between 18-80 feet deep and take 15 years to reach full maturation (~7 lbs.). The oldest recorded living geoduck was 173 years old and can be sexually mature up to 50 years <span class="citation" data-cites="edge2021multicentennial">(<a href="#ref-edge2021multicentennial" role="doc-biblioref">Edge et al. 2021</a>)</span>. Due to their long lives and sexual asynchronicity, they have a low effective population size <span class="citation" data-cites="vadopalas2015maturation">(<a href="#ref-vadopalas2015maturation" role="doc-biblioref">Vadopalas et al. 2015</a>)</span>.</p>
<p>Geoduck clams are an increasingly important fishery and aquaculture product for the Eastern Pacific coast of the US from Baja California to Alaska. The geoduck industry consists of a small number of private operators committed to harvesting, processing, and marketing their product. Geoduck meat is sold primarily outside of the US; siphon meat goes to Japan and Taiwan while body meat is sold in California and the East Coast <span class="citation" data-cites="cheney1986shellfish">(<a href="#ref-cheney1986shellfish" role="doc-biblioref">Cheney and Mumford 1986</a>)</span>. Geoduck aquaculture is considered the most economically important clam fishery in North America <span class="citation" data-cites="hoffman2000modeling">(<a href="#ref-hoffman2000modeling" role="doc-biblioref">Hoffman et al. 2000</a>)</span>, bringing in $24.5 million in sales and over $1 million in state revenue in 2013 <span class="citation" data-cites="washingtonseagrant2015shellfish">(<a href="#ref-washingtonseagrant2015shellfish" role="doc-biblioref">Washington Sea Grant 2015</a>)</span>. Geoduck aquaculture also supports local oyster farming due to its high price per square acre. Recent evidence also suggests that geoduck aquaculture gear can support the recovery of the threatened cockle species in Washington State <span class="citation" data-cites="dimond2022population">(<a href="#ref-dimond2022population" role="doc-biblioref">Dimond et al. 2022</a>)</span>.</p>
<p>Geoducks are primary consumers of phytoplankton by filter feeding. As filter feeders, geoducks provide essential ecosystem services by removing algae, organic matter, and excess nutrients from the water column <span class="citation" data-cites="cubillo2018ecosystem">(<a href="#ref-cubillo2018ecosystem" role="doc-biblioref">Cubillo et al. 2018</a>)</span>. In addition, when geoducks are harvested, excess nutrients such as nitrogen and phosphorus are removed from the marine ecosystem. Geoducks are a keystone species in the subtidal zones, removing organic matter from the environment and providing a food source for the declining populations of sea otters and crabs.</p>
<p>Wild populations have been threatened by overharvesting and poaching <span class="citation" data-cites="kuow2015poaching">(<a href="#ref-kuow2015poaching" role="doc-biblioref">KUOW 2015</a>)</span>. Due to concerns of genetic mixing between hatchery and wild populations, most aquaculture of geoduck is done using wild broodstock, but the potential for genetic mixing still exists. Farmed geoducks may become reproductively mature as early as two years old <span class="citation" data-cites="vadopalas2015maturation">(<a href="#ref-vadopalas2015maturation" role="doc-biblioref">Vadopalas et al. 2015</a>)</span>. Due to these concerns, a key area of research focuses on the reproductive biology of geoduck clams. The use of triploid geoduck clams may help alleviate reproductive maturation in farmed clams, akin to research done on ploidy in Pacific oysters <span class="citation" data-cites="allen1986performance">(<a href="#ref-allen1986performance" role="doc-biblioref">Allen and Downing 1986</a>)</span>. Due to issues with triploidy, there is a need to better understand the reproductive genes responsible for sexual maturation to provide resources for future work developing sterility approaches. This work could include the development of gene knock-down strategies.</p>
<p>The main objective of this study is to build annotated reference transcriptome libraries. There were three specialized tissue types: gonad, ctenidia, and heart. There were two tissue samples from pooled larvae and pooled juveniles as well. In addition, this study also leveraged tools and resources from previously published genome and transcriptome studies on clams from Venerida.</p>
<p>The publication of a fully annotated juvenile <em>P. generosa</em> reference genome <span class="citation" data-cites="putnam2022dynamic">(<a href="#ref-putnam2022dynamic" role="doc-biblioref">Putnam et al. 2022</a>)</span>, along with previous studies focusing on geoduck genomics and gene expression in response to environmental stress, contributes to a comprehensive understanding of geoduck and mollusk genomics while shedding light on the role of DNA methylation in environmental acclimatization. Previous work on geoduck genomics focuses on gene expression in response to environmental stress. Work on the <em>P. globosa</em> juvenile transcriptome exposed to chronic and acute thermal stress demonstrated similar gene expression patterns between stressed and non-stressed animals <span class="citation" data-cites="juarez2018transcriptomic">(<a href="#ref-juarez2018transcriptomic" role="doc-biblioref">Juárez et al. 2018</a>)</span>. In the same study there was also a high degree of expression of genes related to DNA repair and transcription regulation in chronically exposed juveniles, where protective genes against oxidative stress were highly expressed in acutely exposed juveniles. <span class="citation" data-cites="timminsschiffman2017integrating">Timmins-Schiffman et al. (<a href="#ref-timminsschiffman2017integrating" role="doc-biblioref">2017</a>)</span> published the first proteomic study of three maturation stages in male and female geoduck clams using gonad proteins. They showed that gonad proteins became increasingly divergent between males and females as maturation progressed. <span class="citation" data-cites="venkataraman2019larval">Venkataraman et al. (<a href="#ref-venkataraman2019larval" role="doc-biblioref">2019</a>)</span> investigated sex-specific broodstock response and differential gene expression in <em>P. generosa</em> in response to low pH. Temperature and dissolved oxygen increases corresponded to differences in protein abundance patterns such as heat shock protein 90-α. In larvae, <span class="citation" data-cites="timminsschiffman2020dynamic">Timmins-Schiffman et al. (<a href="#ref-timminsschiffman2020dynamic" role="doc-biblioref">2020</a>)</span> looked at the proteomics of larval <em>P. generosa</em> with ciliate infection to investigate the molecular underpinnings of the innate immune response of the larvae to a pathogen. Ciliate response proteins included many associated with ribosomal synthesis and protein translation, suggesting the importance of protein synthesis during larval immune response. In juvenile <em>P. generosa</em>, <span class="citation" data-cites="gurr2020metabolic">Gurr et al. (<a href="#ref-gurr2020metabolic" role="doc-biblioref">2020</a>)</span> and <span class="citation" data-cites="gurr2022acclimatory">Gurr et al. (<a href="#ref-gurr2022acclimatory" role="doc-biblioref">2022</a>)</span> conditioned the animals before testing them with elevated pCO2 (~2400 μatm). Following the secondary exposure, neither elevated nor ambient pCO2 altered juvenile respiration rates, indicating ability for metabolic recovery under subsequent conditions. Recently, <span class="citation" data-cites="putnam2022dynamic">Putnam et al. (<a href="#ref-putnam2022dynamic" role="doc-biblioref">2022</a>)</span> published an annotated <em>P. generosa</em> reference genome as part of a larger common-garden ocean acidification study. They looked at the role of DNA methylation on environmental acclimatization. Functional enrichment analysis of differentially methylated genes revealed regulation of signal transduction that influences cell growth, proliferation, tissue and skeletal formation, and cytoskeletal change. This work, as well as the present study, will greatly aid in the collective understanding of not only geoduck genomics but overall mollusk genomics. In this study, five RNA-seq transcriptome libraries from three geoduck tissue types (gonad, heart, ctenidia) and two different life stages (larvae, juvenile) were assembled and annotated with biological Gene Ontology information. A particular emphasis in this study were reproductive genes and the gonad library, as the most likely location for reproductive genes.</p>
<p>In addition to the five geoduck RNA-seq libraries described in this study, there is also value in leveraging publicly available data for a comparative clam species transcriptome study. <span class="citation" data-cites="mun2017whole">Mun et al. (<a href="#ref-mun2017whole" role="doc-biblioref">2017</a>)</span> published a transcriptome of the Manila clam (<em>Ruditapes philippinarum</em>) as part of a greater effort in selective breeding and disease control. They reported 41,275 annotated sequences in the de novo whole transcriptome assembly of <em>R. philippinarum</em> across three different tissues (foot, gill, and adductor muscle). <span class="citation" data-cites="wang2016clam">Wang et al. (<a href="#ref-wang2016clam" role="doc-biblioref">2016</a>)</span> was the first to publish an annotated transcriptome of the hard clam <em>Mercenaria mercenaria</em>, as part of work investigating the parasite QPX in hard clams. A de novo assembly was constructed and a consensus transcriptome of 62,980 sequences were functionally annotated. A total of 3,131 transcripts were identified as differentially expressed in healthy versus infected tissues. Comparative analysis of annotated genes can reveal the conserved molecular mechanisms between mollusks, such as genes with high homology expressed across the Venerida clade.</p>
<p>Genome resources for clams in the Venerida clade are more abundant than transcriptome or proteomic resources. A reference genome is available in <em>R. philippinarum</em> <span class="citation" data-cites="mun2017whole">(<a href="#ref-mun2017whole" role="doc-biblioref">Mun et al. 2017</a>)</span> and <em>M. mercenaria</em> <span class="citation" data-cites="wang2016clam">(<a href="#ref-wang2016clam" role="doc-biblioref">Wang et al. 2016</a>)</span> as part of the research mentioned above. To leverage even more clam genomic resources, the genomes of <em>Spisula solida</em>, <em>Mactra quadrangularis</em>, and <em>Archivesica marissinica</em> were also compared to <em>P. generosa</em> for functional analysis. The assembly of the surf clam, <em>S. solida</em>, was based on Hi-C data generated as part of the Darwin Tree of Life Project. The other surf clam, <em>Mactra quadrangularis</em> (or <em>Mactra veneriformis</em>), also has a recently assembled genome <span class="citation" data-cites="sun2022high">(<a href="#ref-sun2022high" role="doc-biblioref">Sun et al. 2022</a>)</span>. Low natural yields in <em>M. quadrangularis</em> in China led to this recent effort to better understand surf clam genomic resources. Using Hi-C assembly, a total of 29,315 protein-coding genes were predicted. From this study, a genome-level phylogenetic tree was constructed demonstrating that <em>M. quadrangularis</em> and <em>R. philippinarum</em> diverged around 231 million years ago. In the Northern quahog clam, <em>Mercenaria mercenaria</em>, <span class="citation" data-cites="farhat2022comparative">Farhat et al. (<a href="#ref-farhat2022comparative" role="doc-biblioref">2022</a>)</span> published the first publicly available genome. Due to high environmental variability on the East Coast of the US, and a desire to understand mass mortality events, the genome of <em>M. mercenaria</em> needed to be assembled. Genome annotation yielded 34,728 predicted protein-coding genes, the most of all the Venerida so far. Using these previously published genomic resources by running a comparative genomic analysis will provide an important resource for future comparative work.</p>
<p>Limited studies in bivalve genomics have investigated sexual maturation through differential gene expression in various tissue types. <span class="citation" data-cites="dheilly2012gametogenesis">Dheilly et al. (<a href="#ref-dheilly2012gametogenesis" role="doc-biblioref">2012</a>)</span> looked at the basis of sex differentiation in Pacific oysters (<em>Crassostrea gigas</em>) using a microarray assay. Gene expression was studied in the gonad over a yearly reproductive cycle. There were 2,482 genes found to be differentially expressed between males and females during gametogenesis. The expression of 434 genes could be localized to the germ cells or somatic cells of the gonad and between the sexes. Maturation analysis processes like this study can reveal the conserved and diverged genes between male and female gonads.</p>
<p>Transcriptomics is an important field of study that provides insight into the complex gene expression patterns of various organisms. Comparative transcriptomics allows for a deeper understanding of the differences and similarities in gene expression between different species. In addition to a functional annotation of the geoduck transcriptome, the focus of this study will be to investigate and characterize five different geoduck tissue types (gonad, heart, ctenidia, larvae, and juvenile). We compared the transcriptomes of Manila clams (<em>R. philippinarum</em>), Mercenaria clams (<em>M. mercenaria</em>), and Pacific oysters (<em>Crassostrea gigas</em>) against the geoduck (<em>P. generosa</em>) transcriptome, focusing on the most commonly expressed and overexpressed Gene Ontology (GO) terms and genes. Genomes of five clam species were also compared to the <em>P. generosa</em> genome, looking for genes with high homology. As more clam species are sequenced and genomes assembled, the overall gap in knowledge will decrease and more functional applications for aquaculture can be developed.</p>
</section>
<section id="methods" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="methods"><span class="header-section-number">3</span> Methods</h2>
<p>There is a reference genome of juvenile <em>P. generosa</em> recently published by <span class="citation" data-cites="putnam2022dynamic">Putnam et al. (<a href="#ref-putnam2022dynamic" role="doc-biblioref">2022</a>)</span>. They used the Proximo Hi-C process (Phase Genomics) resulting in 18 chromosome scaffolds containing 1.42 Gbp of sequence (64.53% of the corrected assembly). Juicebox correction resulted in a scaffold N50 of 57,743,597 bp. Genome annotation identified 34,947 genes and 236,960 coding sequence regions which corresponds to 38,326 mRNA features. Genome feature tracks included genes, exons, introns, repetitive sequences, and CG motifs <span class="citation" data-cites="roberts2018opportunities">(<a href="#ref-roberts2018opportunities" role="doc-biblioref">Roberts and Gavery 2018</a>)</span>. Annotation yielded 16,899 tRNAs with a mean and median length of 75 bp in the range of 53-314 bp. CG content was determined to be 33.78% and a total of 15,712,294 CG motifs are present in the genome. The assembled genome is available on the National Center for Biotechnology Information website (NCBI) under GCA_902825435.1. Sequences were annotated by comparing contiguous sequences to the UniProtKB/Swiss-Prot database (<a href="http://uniprot.org" class="uri">http://uniprot.org</a>) using the BLASTn algorithm <span class="citation" data-cites="altschul1997gapped">(<a href="#ref-altschul1997gapped" role="doc-biblioref">Altschul et al. 1997</a>)</span> with a 1.0E-20 e-value threshold. Based on the Swiss-Prot values, there were 14,672 protein-coding sequences in the <em>P. generosa</em> genome that had gene ontology characterization information such as GO enrichment analysis.</p>
<p>Total RNA was extracted from adult, juvenile, and pooled larvae of <em>P. generosa</em>. The adult tissue was isolated using the PAXgene Tissue RNA Kit (Qiagen) based on manufacturer’s instructions. The adult tissue was separated into three different types by function: gonad, ctenidia, and heart. Five RNA-seq libraries were constructed from pooled mRNA and sequenced at the University of Washington High Throughput Genomics Unit (HTGU) on the Illumina Hi-Seq 2000 platform (Illumina, San Diego, CA, USA). Each library was run on a single lane. Raw sequence reads were quality trimmed using Trim Galore v0.4.0, and the sequence data was quality assessed using FastQC <span class="citation" data-cites="andrews2010fastqc">(<a href="#ref-andrews2010fastqc" role="doc-biblioref">Andrews 2010</a>)</span>.</p>
<p>Sequences were annotated by comparing contiguous sequences to the UniProtKB/Swiss-Prot database (<a href="http://uniprot.org" class="uri">http://uniprot.org</a>) using the BLASTn algorithm with a 1.0E-20 e-value threshold. Genes were then classified according to their biological processes, determined by their Gene Ontology (GO) information, and classified into one or more of 72 parent categories (GO slims). The full dataset is available in Supplementary Table 2. Genes were classified into their RNA-seq library (ctenidia, gonad, heart, juvenile, or larvae) and any gene with a transcript per million (tpm) greater than zero was retained for analysis. Gene Ontology terms were then characterized relative to all Gene Ontology terms (GO slims) present in the <em>P. generosa</em> genome. A new term was calculated by taking the proportion of a single GO slim present in an RNA-seq library over the proportion of that same GO slim present in the entire <em>P. generosa</em> gene set. We coined this new term the “Gene Ontology Proportional Value”, where, for example, when the proportional value equals one, the GO slim in the RNA-seq library is representative of the GO slim in the entire gene repertoire.</p>
<p><em>M. mercenaria</em> and <em>R. philippinarum</em> transcriptomes were annotated by comparing sequences to the entire gene list of <em>P. generosa</em> and given Gene Ontology Proportional Values for inter-species comparison. Transcriptome libraries were obtained from NCBI (<em>R. philippinarum</em> GenBank accession GCA_026571515.1 and <em>M. mercenaria</em> accession GCF_021730395.1). Gene lists were annotated using BLASTn with an e-value of 1E-20 and associated Gene Ontology terms classified and counted by transcriptome library (either <em>M. mercenaria</em> or <em>R. philippinarum</em>). Gene Ontology terms were then classified using the same process as the geoduck sequence analysis above. The Gene Ontology Proportional Value was calculated using the proportion of GO slims present in either <em>M. mercenaria</em> or <em>R. philippinarum</em> transcriptome libraries relative to the proportion of that same GO slim present in the entire <em>P. generosa</em> transcriptome library.</p>
<p>In order to see if there was a functional difference between genes with high homology, five different clam genomes in the Venerida family were annotated: <em>Archivesica marissinica</em> (GenBank GCA_014843695.1), <em>Mactra quadrangularis</em> (GCA_025267735.1), <em>Mercenaria mercenaria</em> (GCF_021730395.1), <em>Ruditapes philippinarum</em> (GCA_026571515.1), and <em>Spisula solida</em> (GCA_947247005.1). All five clam genomes were annotated by comparing contiguous sequences to the <em>P. generosa</em> gene database using the BLASTn algorithm with a 1.0E-20 e-value threshold.</p>
<p>Characterization of reproductive genes in <em>P. generosa</em> was done in two ways. The first was to gather a list of genes expressed in the gonad. This produced a list of reproductive genes in the <em>P. generosa</em> adult gonad that code for proteins related to “reproductive process” functions (Supplementary Table 3).</p>
<p><span class="citation" data-cites="dheilly2012gametogenesis">Dheilly et al. (<a href="#ref-dheilly2012gametogenesis" role="doc-biblioref">2012</a>)</span> investigated the temporal variation of gene expression during oyster gonad differentiation and development in <em>C. gigas</em>. The genes identified in their oyster study are differentiated by sex and stage of development: somatic tissues and oocytes. Differentially expressed oyster gonad and oocyte genes were pulled from their Supplementary Table 3. GenBank accession numbers were gathered from clusters 1-10 and were annotated against the <em>P. generosa</em> gene database using the BLASTn algorithm with a 1.0E-10 e-value threshold. The focus of this analysis was the female reproductive genes from developmental stage 0 to stage 3, compared to the reproductive genes found in the RNA-seq gonad library.</p>
</section>
<section id="results" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="results"><span class="header-section-number">4</span> Results</h2>
<p>After leveraging the genomic resources from <span class="citation" data-cites="putnam2022dynamic">Putnam et al. (<a href="#ref-putnam2022dynamic" role="doc-biblioref">2022</a>)</span> to compare to the Swiss-Prot database, a fully annotated genome-linked transcriptome was produced. This genome has 34,947 annotated protein-coding sequences. Of those, 2,180 are expressed only in the juveniles. The RNA-seq library for larval geoduck returned 19,449 genes with 868 genes found only in the larval transcriptome library. In the heart library, there were 17,479 genes representing only 371 genes unique to the heart. In the ctenidia, there were 17,479 genes representing 340 genes found only in the ctenidia tissue library. Most crucially for this study on reproduction, the gonad RNA-seq library had the fewest genes, with only 13,682. Of those genes, 119 were found uniquely expressed in the gonad. The full annotation of the five RNA-seq libraries is found in Supplementary Table 2. A pairwise comparison between RNA-seq libraries was produced from the unique gene list above, represented as a count of biological gene ontology terms (Supplementary Figure 2).</p>
<p>Expanding out from gene characterization, the Gene Ontology Proportional Value is descriptive of the abundance of biological Gene Ontology processes per library relative to the entire <em>P. generosa</em> genome (<a href="#fig-go-proportion" class="quarto-xref">Figure&nbsp;1</a>). In the <em>P. generosa</em> genome, there are 17,611 GO slims representing 34,947 genes. In the juvenile, there are 17,277 GO slims representing 19,449 genes. In the larvae, there are 16,632 GO slims representing 19,449 genes. In the heart there are 16,021 GO slims representing 17,602 genes. In the ctenidia, there are 15,911 GO slims representing 17,479 genes. Finally, in the gonad there are 14,715 GO slims representing 13,682 genes.</p>
<div id="fig-go-proportion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-go-proportion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig-go-proportion-heatmap.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-go-proportion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Relative abundance of gene ontology terms compared to the entire geoduck genome, where value = Gene Ontology Proportional Value. Values highlighted in green or red represent an under- or over-abundant Biological Gene Ontology Term relative to the entire geoduck gene repertoire, respectively.
</figcaption>
</figure>
</div>
<p>Annotations from the <em>M. mercenaria</em> and <em>R. philippinarum</em> transcript libraries against the <em>P. generosa</em> gene list revealed a strong phylogenetic correlation between <em>P. generosa</em> and <em>M. mercenaria</em>. Of the 34,947 mRNA features in the <em>P. generosa</em> transcriptome, 5,099 (14.6%) were found in the <em>M. mercenaria</em> transcriptome. In contrast, only 657 (1.8%) mRNA features were found in the <em>R. philippinarum</em> transcriptome. The transcript libraries of <em>M. mercenaria</em> and <em>R. philippinarum</em> were annotated with Gene Ontology Proportional Values. In <em>M. mercenaria</em> transcript libraries there are 7,027 GO slims, while in <em>R. philippinarum</em> there are only 1,390 GO slims. The most abundant GO slim categories were anatomical structure development, signaling, and cell differentiation. For example, of the 456 genes shared between <em>P. generosa</em> and <em>M. mercenaria</em>, the most abundant were related to anatomical structure development, while only 67 genes related to anatomical structure development were shared between <em>P. generosa</em> and <em>R. philippinarum</em>.</p>
<p>Annotations from other clam genomes against the <em>P. generosa</em> genome further highlighted genomic homology (<a href="#tbl-genome-comparison" class="quarto-xref">Table&nbsp;1</a>). The <em>M. mercenaria</em> genome is 1.9 Gb and the CG content was determined to be 34.5%. Of the 34,947 genes in <em>P. generosa</em>, 8,736 genes were matched in <em>M. mercenaria</em>, the most matches of all five genomes. The <em>R. philippinarum</em> genome is 1.4 Gb and the CG content was determined to be 32%; 2,263 genes found in <em>P. generosa</em> were matched in <em>R. philippinarum</em>. The <em>A. marissinica</em> genome is 1.5 Gb and the CG content was determined to be 39%; of those genes in <em>P. generosa</em>, 3,268 were matched to <em>A. marissinica</em>. <em>S. solida</em> is a smaller genome at 932 Mb, with a CG content of 35.5%, and 1,629 genes matched to the <em>P. generosa</em> genome. The <em>M. quadrangularis</em> annotated genome is the smallest of the five with a size of only 979 Mb, a CG content of 33%, and only 874 gene matches to the <em>P. generosa</em> gene set.</p>
<div id="tbl-genome-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-genome-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Genome size, CG content, and number of genes matched to the <em>P. generosa</em> gene set for five Venerida clam genomes.
</figcaption>
<div aria-describedby="tbl-genome-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Species</th>
<th>Genome size</th>
<th>CG content</th>
<th>Genes matched to <em>P. generosa</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Mercenaria mercenaria</em></td>
<td>1.9 Gb</td>
<td>34.5%</td>
<td>8,736</td>
</tr>
<tr class="even">
<td><em>Archivesica marissinica</em></td>
<td>1.5 Gb</td>
<td>39%</td>
<td>3,268</td>
</tr>
<tr class="odd">
<td><em>Ruditapes philippinarum</em></td>
<td>1.4 Gb</td>
<td>32%</td>
<td>2,263</td>
</tr>
<tr class="even">
<td><em>Spisula solida</em></td>
<td>932 Mb</td>
<td>35.5%</td>
<td>1,629</td>
</tr>
<tr class="odd">
<td><em>Mactra quadrangularis</em></td>
<td>979 Mb</td>
<td>33%</td>
<td>874</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-genome-coverage" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-genome-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig-genome-coverage.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-genome-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Percent coverage of the <em>P. generosa</em> gene list represented in the five clam genomes: <em>Mercenaria mercenaria</em>, <em>Archivesica marissinica</em>, <em>Ruditapes philippinarum</em>, <em>Spisula solida</em>, and <em>Mactra quadrangularis</em>.
</figcaption>
</figure>
</div>
<p>Characterization of reproductive genes in <em>P. generosa</em> was done in two ways. The first was to gather a list of genes expressed in the gonad. This produced a list of reproductive genes in the <em>P. generosa</em> adult gonad coding for proteins related to “reproductive process” functions (Supplementary Table 3). Of the 34,947 genes in the <em>P. generosa</em> gene list, 640 genes are involved with the reproductive process (1.8% reproductive).</p>
<p>Leveraging <span class="citation" data-cites="dheilly2012gametogenesis">Dheilly et al. (<a href="#ref-dheilly2012gametogenesis" role="doc-biblioref">2012</a>)</span> results from 32 individual gonad samples of <em>C. gigas</em>, they identified 2,482 genes differentially expressed between gametogenesis stages. Of those, 511 genes were found to be expressed in major expression stage 0 of development (neither male nor female). Of those 511 oyster reproductive genes, 7 geoduck reproductive genes were found in the <em>P. generosa</em> genome. Key genes from stage 0 are <em>Ttn</em>, <em>BMP2</em>, and <em>ZNF107</em>. In the next developmental stage, major expression stages 1-3 for females, there were 197 genes differentially expressed in oysters. Of those 197 genes, 5 candidate genes were found in <em>P. generosa</em>. The only candidate gene from stages 1-3 is <em>Rusf1</em>. In the later developmental stages 2-3, <span class="citation" data-cites="dheilly2012gametogenesis">Dheilly et al. (<a href="#ref-dheilly2012gametogenesis" role="doc-biblioref">2012</a>)</span> found 312 candidate reproductive genes, and of those 312, we found 13 candidate genes. Key candidate genes from this developmental stage are <em>SMC5</em>, <em>Cep57</em>, <em>KCTD5</em>, <em>ATF7IP</em>, and <em>TPST1</em>. In the final developmental stage 3, <span class="citation" data-cites="dheilly2012gametogenesis">Dheilly et al. (<a href="#ref-dheilly2012gametogenesis" role="doc-biblioref">2012</a>)</span> reported 222 reproductive genes. Our annotation revealed 14 <em>P. generosa</em> reproductive genes including <em>STOX1</em>, <em>SPPL3</em>, <em>Wdr20</em>, and <em>Rere</em>. There were also two <em>P. generosa</em> genes found in cluster 9 (female and male differentially expressed gametogenesis stages) that were specific to the female gonad tissue. Those genes were <em>SUMO3</em> and <em>ARHGAP11A</em>.</p>
</section>
<section id="discussion" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="discussion"><span class="header-section-number">5</span> Discussion</h2>
<p>The generation of five fully characterized RNA-seq libraries provides comprehensive insights into gene expression patterns, ultimately advancing our understanding of Pacific geoduck reproductive biology and gene expression profiles. These transcript libraries are beneficial to describing individual tissue functions, as the unique sets of genes found in each tissue type are consistent with their specialized functions. For example, the heart tissue had a unique set of genes involved in muscle and renal system processes, which are important for its role in circulation <span class="citation" data-cites="drake2012amino">(<a href="#ref-drake2012amino" role="doc-biblioref">Drake et al. 2012</a>)</span>. The ctenidia tissue had a unique set of genes involved in DNA repair, which is likely important for its role in filtering and cleaning the water that the geoduck lives in <span class="citation" data-cites="juarez2018transcriptomic">(<a href="#ref-juarez2018transcriptomic" role="doc-biblioref">Juárez et al. 2018</a>)</span>. The larval library had a unique set of genes involved in nucleobase-containing small molecule metabolic processes and cytoskeleton organization. The juvenile library was the largest, with 67.01% of genes expressed relative to the entire gene list of geoduck, representing almost all of the relevant biological processes.</p>
<p>We found that each tissue type exhibited a distinct set of expressed genes, indicating unique functional roles. These genes are categorized into their biological gene ontology (GO) processes by their Gene Ontology Proportional Value into over-abundant or under-abundant relative to the entire <em>P. generosa</em> genome. The most commonly over-abundant GO processes distinct to all tissue types were related to metabolism, gene expression, and protein making (<a href="#fig-go-proportion" class="quarto-xref">Figure&nbsp;1</a>), indicating that metabolism is more important at the specialized tissue level for geoduck. The most common under-abundant GO processes were related to specialized system processes such as renal, endocrine, digestive, and circulatory systems. This is unsurprising, as digestive biological processes are going to be under-expressed in tissue types that don’t specialize in digestion. Most of the over-abundant GO processes unique to specific tissue types were functional to their specific needs. For example, in the gonad, the top over-abundant GO processes were related to mitochondria and metabolism, while in the larvae the top over-abundant GO processes were related to movement and energy allocation systems. For the heart, the top over-abundant GO processes were related to nitrogen cycle metabolism, agreeing with its main function as a mechanical pump as well as its electrical activity <span class="citation" data-cites="drake2012amino">(<a href="#ref-drake2012amino" role="doc-biblioref">Drake et al. 2012</a>)</span>. For the ctenidia, the top over-abundant GO processes were related to cytoplasmic translation. Cytoplasmic translation refers to the process by which mRNA molecules are translated into proteins in the cytoplasm of the cell. This process is important in many cells, including those in the ctenidia, because it allows for rapid and efficient protein synthesis <span class="citation" data-cites="mclean1974rna">(<a href="#ref-mclean1974rna" role="doc-biblioref">McLean and Whiteley 1974</a>)</span>. The juvenile tissue types did not have any highly over-abundant genes due to their later developmental stage.</p>
<p>Investigating the annotated transcriptome libraries shared between <em>P. generosa</em> and <em>M. mercenaria</em> or <em>R. philippinarum</em> further illuminates foundational gene expression of <em>P. generosa</em>. Genes involved with translation, microtubule-based movement, and cilium organization are all highly expressed in both the <em>M. mercenaria</em> and the <em>R. philippinarum</em> libraries. Interestingly, there is a unique group of conserved genes in <em>M. mercenaria</em> and <em>P. generosa</em> that are not found in <em>R. philippinarum</em>. These genes were related to metabolism and cellular organization. These differences, as well as <em>M. mercenaria</em> having more shared genes than <em>R. philippinarum</em>, may be due to <em>M. mercenaria</em> being a closer phylogenetic relation to <em>P. generosa</em> than <em>R. philippinarum</em> <span class="citation" data-cites="chen2011molecular">(<a href="#ref-chen2011molecular" role="doc-biblioref">Chen et al. 2011</a>)</span>. The inter-species analysis is valuable in determining gene orthologs important for reproduction investigations. Cross-species library comparison is also useful for future studies on gene function in marine bivalves outside of reproductive control, such as studies involving disease tolerance.</p>
<p>In the <em>P. generosa</em> genome from <span class="citation" data-cites="putnam2022dynamic">Putnam et al. (<a href="#ref-putnam2022dynamic" role="doc-biblioref">2022</a>)</span>, they found the geoduck genome to be almost 2 times larger in size than oyster genomes, with twice as many putative chromosomes. This trend reversed when comparing <em>P. generosa</em> to other clam genomes. <em>R. philippinarum</em>, <em>M. mercenaria</em>, and <em>A. marissinica</em> all have genomes larger than <em>P. generosa</em> and an additional chromosome. Interestingly, regardless of genome size, the relative number of genes was approximately the same (~30,000). The GC content was also highly conserved across species at 32-33% (except for <em>A. marissinica</em> at 39%). Comparing the percent coverage of the <em>P. generosa</em> gene list to the query sequences of the other five clam genomes, <em>A. marissinica</em>, <em>R. philippinarum</em>, and <em>S. solida</em> have shared gene lists with <em>P. generosa</em> of 3,268, 2,263, and 1,629 respectively. <em>M. mercenaria</em> has the most shared genes with <em>P. generosa</em> at 8,736, and <em>M. quadrangularis</em> the least with only 874 (<a href="#fig-genome-coverage" class="quarto-xref">Figure&nbsp;2</a>). Looking at the phylogenetic relationship between <em>M. mercenaria</em> and <em>R. philippinarum</em> <span class="citation" data-cites="chen2011molecular">(<a href="#ref-chen2011molecular" role="doc-biblioref">Chen et al. 2011</a>)</span> reveals that <em>R. philippinarum</em> is more basal than <em>M. mercenaria</em>. As more genomes are fully annotated and made available on NCBI, comparative studies like this will be more robust.</p>
<p>A key emphasis of this study was to describe reproductive genes in geoduck. Our first approach, using the gonad RNA-seq library, produced a moderately large set of genes (n = 640) with gene expression patterns related to the reproductive process. This is consistent with previous studies <span class="citation" data-cites="timminsschiffman2017integrating">(<a href="#ref-timminsschiffman2017integrating" role="doc-biblioref">Timmins-Schiffman et al. 2017</a>)</span> that have shown reproductive tissues often have unique gene expression profiles. Leveraging the results of <span class="citation" data-cites="dheilly2012gametogenesis">Dheilly et al. (<a href="#ref-dheilly2012gametogenesis" role="doc-biblioref">2012</a>)</span> provided a list of reproductive genes found in geoducks (74) that are linked to a major expression stage by sex and developmental stage. Looking at highly conserved reproductive genes across species gives us confidence that these are homologous genes for controlling reproduction in Bivalvia. <span class="citation" data-cites="dheilly2012gametogenesis">Dheilly et al. (<a href="#ref-dheilly2012gametogenesis" role="doc-biblioref">2012</a>)</span> described reproductive genes related to mitosis and meiosis regulation, including centromere proteins and kinesin-related proteins. In the <em>P. generosa</em> transcriptional dataset, reproductive genes related to centromere and kinesin-related proteins were: Kinesin-like protein 6, KIF18A, and KIF9, inner centromere protein, centromere protein zw10 homolog, and centromere-associated proteins S, E, and X. <span class="citation" data-cites="dheilly2012gametogenesis">Dheilly et al. (<a href="#ref-dheilly2012gametogenesis" role="doc-biblioref">2012</a>)</span> identified genes associated with female-specific processes such as oogenesis, including vitellogenin, cd63, mitotic apparatus, p62, forkhead box L2, and caveolin. In <em>P. generosa</em>, reproductive genes related to oogenesis were: putative vitellogenin receptor (protein yolkless), forkhead box protein C1 and J3, and RecQ-mediated genome instability protein 1 (M-caveolin).</p>
<p>Between the two approaches for identifying key reproductive genes in <em>P. generosa</em>, there are two genes found using both: <em>Foxl1</em> and <em>Cep57</em>. The <em>Fox</em> genes, which code for forkhead-class transcription factors, are classical orthologs involved in sex determination/differentiation <span class="citation" data-cites="broquard2021gonadal">(<a href="#ref-broquard2021gonadal" role="doc-biblioref">Broquard et al. 2021</a>)</span>. <span class="citation" data-cites="dheilly2012gametogenesis">Dheilly et al. (<a href="#ref-dheilly2012gametogenesis" role="doc-biblioref">2012</a>)</span> found forkhead box L2 genes in <em>C. gigas</em>. Many studies on bivalves have found this gene to be involved in reproduction, having been found in <em>C. gigas</em> and the pearl oyster <em>Pinctada fucata</em>, as well as other bivalves <span class="citation" data-cites="matsumoto2013reproduction">(<a href="#ref-matsumoto2013reproduction" role="doc-biblioref">Matsumoto et al. 2013</a>)</span>. The <em>Cep57</em> gene, which codes for centrosome- and midbody-associated proteins, is not commonly studied for its implications in reproduction in bivalves. A similar ortholog, <em>Cep55</em>, has been documented to be involved in embryonic development in zebrafish <span class="citation" data-cites="jeffery2015cep55">(<a href="#ref-jeffery2015cep55" role="doc-biblioref">Jeffery et al. 2015</a>)</span>, and should be the focus of study in bivalve reproduction going forward. In particular, genes related to vitellogenin, caveolin, forkhead-class transcription factors, and Cep55/57 all appear to be highly conserved across Bivalvia and are very closely related to reproductive development.</p>
<p>Our results provide a foundation for future studies aimed at understanding the molecular basis of geoduck (<em>Panopea generosa</em>) physiology and development. Comparative analysis with Mercenaria clam and Manila clam transcript libraries provided insights into gene orthologs and conserved functions across species. Annotated RNA-seq libraries facilitated the identification of tissue-specific genes, including a significant number of previously undiscovered reproductive genes in geoduck. Specifically, forkhead and Cep55/57 genes are key genes found. Each tissue type exhibited distinct sets of expressed genes, reflecting their specialized functions. Over-abundant biological gene ontology (GO) terms in all tissue types were related to metabolism, gene expression, and protein synthesis, highlighting the importance of these processes at the tissue level. The study also focused on identifying reproductive genes for potential gene editing efforts, highlighting key genes involved in sex determination, oogenesis, and embryonic development. Overall, these findings lay the groundwork for future studies investigating geoduck physiology, development, and reproductive control, as well as broader investigations into gene function and disease tolerance in marine bivalves. By identifying these tissue-specific gene expression patterns, we can begin to unravel the complex molecular networks that underlie geoduck biology.</p>
</section>
<section id="data-and-code-availability" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="data-and-code-availability"><span class="header-section-number">6</span> Data and code availability</h2>
<p>The juvenile <em>P. generosa</em> reference genome is available on NCBI under accession GCA_902825435.1. Comparative genomes and transcriptomes were obtained from NCBI: <em>Ruditapes philippinarum</em> (GCA_026571515.1), <em>Mercenaria mercenaria</em> (GCF_021730395.1), <em>Archivesica marissinica</em> (GCA_014843695.1), <em>Mactra quadrangularis</em> (GCA_025267735.1), and <em>Spisula solida</em> (GCA_947247005.1). Supplementary tables and figures referenced here are part of the original thesis.</p>
</section>
<section id="suggested-citation" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="suggested-citation"><span class="header-section-number">7</span> Suggested citation</h2>
<p>Cattau, O., and S. B. Roberts. 2023. <em>Comparative Genomic Analysis of Geoduck Clam (Panopea generosa)</em>. Current Findings. Available at: https://robertslab.github.io/current-findings/reports/geoduck-comparative-genomics/</p>
</section>
<section id="version-history" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="version-history"><span class="header-section-number">8</span> Version history</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Version</th>
<th>Date</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.1</td>
<td>2026-06-17</td>
<td>Migrated from Cattau_washington_0250O_25940.pdf (M.S. thesis Chapter 2)</td>
</tr>
</tbody>
</table>
</section>
<section id="references" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="references"><span class="header-section-number">9</span> References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-allen1986performance" class="csl-entry" role="listitem">
Allen, S. K., and S. L. Downing. 1986. <span>“Performance of Triploid Pacific Oysters, Crassostrea Gigas (Thunberg). I. Survival, Growth, Glycogen Content, and Sexual Maturation in Yearlings.”</span> <em>Journal of Experimental Marine Biology and Ecology</em> 102 (2–3): 197–208. <a href="https://doi.org/10.1016/0022-0981(86)90176-0">https://doi.org/10.1016/0022-0981(86)90176-0</a>.
</div>
<div id="ref-altschul1997gapped" class="csl-entry" role="listitem">
Altschul, S. F., T. L. Madden, A. A. Schäffer, et al. 1997. <span>“Gapped BLAST and PSI-BLAST: A New Generation of Protein Database Search Programs.”</span> <em>Nucleic Acids Research</em> 25 (17): 3389–402. <a href="https://doi.org/10.1093/nar/25.17.3389">https://doi.org/10.1093/nar/25.17.3389</a>.
</div>
<div id="ref-andrews2010fastqc" class="csl-entry" role="listitem">
Andrews, S. 2010. <em>FastQC: A Quality Control Tool for High Throughput Sequence Data</em>.
</div>
<div id="ref-broquard2021gonadal" class="csl-entry" role="listitem">
Broquard, C., S. Saowaros, M. Lepoittevin, et al. 2021. <span>“Gonadal Transcriptomes Associated with Sex Phenotypes Provide Potential Male and Female Candidate Genes of Sex Determination or Early Differentiation in Crassostrea Gigas, a Sequential Hermaphrodite Mollusc.”</span> <em>BMC Genomics</em> 22 (1): 609. <a href="https://doi.org/10.1186/s12864-021-07838-1">https://doi.org/10.1186/s12864-021-07838-1</a>.
</div>
<div id="ref-chen2011molecular" class="csl-entry" role="listitem">
Chen, J., Q. Li, L. Kong, and X. Zheng. 2011. <span>“Molecular Phylogeny of Venus Clams (Mollusca, Bivalvia, Veneridae) with Emphasis on the Systematic Position of Taxa Along the Coast of Mainland China.”</span> <em>Zoologica Scripta</em> 40 (3): 260–71. <a href="https://doi.org/10.1111/j.1463-6409.2011.00471.x">https://doi.org/10.1111/j.1463-6409.2011.00471.x</a>.
</div>
<div id="ref-cheney1986shellfish" class="csl-entry" role="listitem">
Cheney, Daniel P., and Thomas F. Mumford. 1986. <em>Shellfish and Seaweed Harvests of Puget Sound</em>. The University of Washington Press.
</div>
<div id="ref-cubillo2018ecosystem" class="csl-entry" role="listitem">
Cubillo, A. M., J. G. Ferreira, C. M. Pearce, R. Marshall, D. Cheney, and B. Hudson. 2018. <span>“Ecosystem Services of Geoduck Farming in South Puget Sound, USA: A Modeling Analysis.”</span> <em>Aquaculture International</em> 26 (6): 1427–43. <a href="https://doi.org/10.1007/s10499-018-0291-x">https://doi.org/10.1007/s10499-018-0291-x</a>.
</div>
<div id="ref-dheilly2012gametogenesis" class="csl-entry" role="listitem">
Dheilly, N. M., C. Lelong, A. Huvet, et al. 2012. <span>“Gametogenesis in the Pacific Oyster Crassostrea Gigas: A Microarrays-Based Analysis Identifies Sex and Stage Specific Genes.”</span> <em>PLoS ONE</em> 7 (5): e36353. <a href="https://doi.org/10.1371/journal.pone.0036353">https://doi.org/10.1371/journal.pone.0036353</a>.
</div>
<div id="ref-dimond2022population" class="csl-entry" role="listitem">
Dimond, J. L., R. N. Crim, E. Unsell, V. Barry, and J. E. Toft. 2022. <span>“Population Genomics of the Basket Cockle Clinocardium Nuttallii in the Southern Salish Sea: Assessing Genetic Risks of Stock Enhancement for a Culturally Important Marine Bivalve.”</span> <em>Evolutionary Applications</em> 15 (3): 459–70. <a href="https://doi.org/10.1111/eva.13359">https://doi.org/10.1111/eva.13359</a>.
</div>
<div id="ref-drake2012amino" class="csl-entry" role="listitem">
Drake, K. J., V. Y. Sidorov, O. P. McGuinness, D. H. Wasserman, and J. P. Wikswo. 2012. <span>“Amino Acids as Metabolic Substrates During Cardiac Ischemia.”</span> <em>Experimental Biology and Medicine</em> 237 (12): 1369–78. <a href="https://doi.org/10.1258/ebm.2012.012025">https://doi.org/10.1258/ebm.2012.012025</a>.
</div>
<div id="ref-edge2021multicentennial" class="csl-entry" role="listitem">
Edge, D. C., D. J. Reynolds, A. D. Wanamaker, et al. 2021. <span>“A Multicentennial Proxy Record of Northeast Pacific Sea Surface Temperatures from the Annual Growth Increments of Panopea Generosa.”</span> <em>Paleoceanography and Paleoclimatology</em> 36 (9): e2021PA004291. <a href="https://doi.org/10.1029/2021PA004291">https://doi.org/10.1029/2021PA004291</a>.
</div>
<div id="ref-farhat2022comparative" class="csl-entry" role="listitem">
Farhat, S., E. Bonnivard, E. Pales Espinosa, et al. 2022. <span>“Comparative Analysis of the Mercenaria Mercenaria Genome Provides Insights into the Diversity of Transposable Elements and Immune Molecules in Bivalve Mollusks.”</span> <em>BMC Genomics</em> 23 (1). <a href="https://doi.org/10.1186/s12864-021-08262-1">https://doi.org/10.1186/s12864-021-08262-1</a>.
</div>
<div id="ref-feldman2004comprehensive" class="csl-entry" role="listitem">
Feldman, K., B. Vadopalas, D. Armstrong, et al. 2004. <em>Comprehensive Literature Review and Synopsis of Issues Relating to Geoduck (Panopea Abrupta) Ecology and Aquaculture Production</em>.
</div>
<div id="ref-gurr2022acclimatory" class="csl-entry" role="listitem">
Gurr, S. J., S. A. Trigg, B. Vadopalas, S. B. Roberts, and H. M. Putnam. 2022. <span>“Acclimatory Gene Expression of Primed Clams Enhances Robustness to Elevated pCO2.”</span> <em>Molecular Ecology</em> 31 (19): 5005–23. <a href="https://doi.org/10.1111/mec.16644">https://doi.org/10.1111/mec.16644</a>.
</div>
<div id="ref-gurr2020metabolic" class="csl-entry" role="listitem">
Gurr, S. J., B. Vadopalas, S. B. Roberts, and H. M. Putnam. 2020. <span>“Metabolic Recovery and Compensatory Shell Growth of Juvenile Pacific Geoduck Panopea Generosa Following Short-Term Exposure to Acidified Seawater.”</span> <em>Conservation Physiology</em> 8 (1). <a href="https://doi.org/10.1093/conphys/coaa024">https://doi.org/10.1093/conphys/coaa024</a>.
</div>
<div id="ref-hoffman2000modeling" class="csl-entry" role="listitem">
Hoffman, A., A. Bradbury, and C. L. Goodwin. 2000. <span>“Modeling Geoduck, Panopea Abrupta (Conrad 1849) Population Dynamics.”</span> <em>Journal of Shellfish Research</em> 19: 57–62.
</div>
<div id="ref-jeffery2015cep55" class="csl-entry" role="listitem">
Jeffery, J., C. Neyt, W. Moore, et al. 2015. <span>“Cep55 Regulates Embryonic Growth and Development by Promoting Akt Stability in Zebrafish.”</span> <em>FASEB Journal</em> 29 (5): 1999–2009. <a href="https://doi.org/10.1096/fj.14-265090">https://doi.org/10.1096/fj.14-265090</a>.
</div>
<div id="ref-juarez2018transcriptomic" class="csl-entry" role="listitem">
Juárez, O. E., F. Lafarga-De la Cruz, I. Leyva-Valencia, et al. 2018. <span>“Transcriptomic and Metabolic Response to Chronic and Acute Thermal Exposure of Juvenile Geoduck Clams Panopea Globosa.”</span> <em>Marine Genomics</em> 42: 1–13. <a href="https://doi.org/10.1016/j.margen.2018.09.003">https://doi.org/10.1016/j.margen.2018.09.003</a>.
</div>
<div id="ref-kuow2015poaching" class="csl-entry" role="listitem">
KUOW. 2015. <em>Poaching 100-Year-Old Geoducks for Big Money</em>. <a href="https://www.kuow.org/stories/poaching-100-year-old-geoducks-big-money/" class="uri">Https://www.kuow.org/stories/poaching-100-year-old-geoducks-big-money/</a>.
</div>
<div id="ref-matsumoto2013reproduction" class="csl-entry" role="listitem">
Matsumoto, T., T. Masaoka, A. Fujiwara, Y. Nakamura, N. Satoh, and M. Awaji. 2013. <span>“Reproduction-Related Genes in the Pearl Oyster Genome.”</span> <em>Zoological Science</em> 30 (10): 826–50. <a href="https://doi.org/10.2108/zsj.30.826">https://doi.org/10.2108/zsj.30.826</a>.
</div>
<div id="ref-mclean1974rna" class="csl-entry" role="listitem">
McLean, K. W., and A. H. Whiteley. 1974. <span>“RNA Synthesis During the Early Development of the Pacific Oyster, Crassostrea Gigas.”</span> <em>Experimental Cell Research</em> 87 (1): 132–38. <a href="https://doi.org/10.1016/0014-4827(74)90534-5">https://doi.org/10.1016/0014-4827(74)90534-5</a>.
</div>
<div id="ref-mun2017whole" class="csl-entry" role="listitem">
Mun, S., Y. J. Kim, K. Markkandan, et al. 2017. <span>“The Whole-Genome and Transcriptome of the Manila Clam (Ruditapes Philippinarum).”</span> <em>Genome Biology and Evolution</em> 9 (6): 1487–98. <a href="https://doi.org/10.1093/gbe/evx096">https://doi.org/10.1093/gbe/evx096</a>.
</div>
<div id="ref-putnam2022dynamic" class="csl-entry" role="listitem">
Putnam, H. M., S. A. Trigg, S. J. White, et al. 2022. <span>“Dynamic DNA Methylation Contributes to Carryover Effects and Beneficial Acclimatization in Geoduck Clams.”</span> <em>bioRxiv</em>, ahead of print. <a href="https://doi.org/10.1101/2022.06.24.497506">https://doi.org/10.1101/2022.06.24.497506</a>.
</div>
<div id="ref-roberts2018opportunities" class="csl-entry" role="listitem">
Roberts, S. B., and M. R. Gavery. 2018. <span>“Opportunities in Functional Genomics: A Primer on Lab and Computational Aspects.”</span> <em>Journal of Shellfish Research</em> 37 (4): 747–54. <a href="https://doi.org/10.2983/035.037.0406">https://doi.org/10.2983/035.037.0406</a>.
</div>
<div id="ref-sun2022high" class="csl-entry" role="listitem">
Sun, Y., X. Liu, X. Xie, et al. 2022. <span>“A High-Quality Chromosome-Level Genome Assembly of the Bivalve Mollusk Mactra Veneriformis.”</span> <em>G3: Genes, Genomes, Genetics</em> 12 (11). <a href="https://doi.org/10.1093/g3journal/jkac229">https://doi.org/10.1093/g3journal/jkac229</a>.
</div>
<div id="ref-timminsschiffman2017integrating" class="csl-entry" role="listitem">
Timmins-Schiffman, E. B., G. A. Crandall, B. Vadopalas, M. E. Riffle, B. L. Nunn, and S. B. Roberts. 2017. <span>“Integrating Discovery-Driven Proteomics and Selected Reaction Monitoring to Develop a Noninvasive Assay for Geoduck Reproductive Maturation.”</span> <em>Journal of Proteome Research</em> 16 (9): 3298–309. <a href="https://doi.org/10.1021/acs.jproteome.7b00288">https://doi.org/10.1021/acs.jproteome.7b00288</a>.
</div>
<div id="ref-timminsschiffman2020dynamic" class="csl-entry" role="listitem">
Timmins-Schiffman, E., J. M. Guzmán, R. Elliott Thompson, B. Vadopalas, B. Eudeline, and S. B. Roberts. 2020. <span>“Dynamic Response in the Larval Geoduck (Panopea Generosa) Proteome to Elevated pCO2.”</span> <em>Ecology and Evolution</em> 10 (1): 185–97. <a href="https://doi.org/10.1002/ece3.5885">https://doi.org/10.1002/ece3.5885</a>.
</div>
<div id="ref-vadopalas2015maturation" class="csl-entry" role="listitem">
Vadopalas, B., J. P. Davis, and C. S. Friedman. 2015. <span>“Maturation, Spawning, and Fecundity of the Farmed Pacific Geoduck Panopea Generosa in Puget Sound, Washington.”</span> <em>Journal of Shellfish Research</em> 34 (1): 31–37. <a href="https://doi.org/10.2983/035.034.0106">https://doi.org/10.2983/035.034.0106</a>.
</div>
<div id="ref-venkataraman2019larval" class="csl-entry" role="listitem">
Venkataraman, Y. R., L. H. Spencer, and S. B. Roberts. 2019. <span>“Larval Response to Parental Low pH Exposure in the Pacific Oyster Crassostrea Gigas.”</span> <em>Journal of Shellfish Research</em> 38 (3): 743–50. <a href="https://doi.org/10.2983/035.038.0325">https://doi.org/10.2983/035.038.0325</a>.
</div>
<div id="ref-wang2016clam" class="csl-entry" role="listitem">
Wang, K., C. del Castillo, E. Corre, E. P. Espinosa, and B. Allam. 2016. <span>“Clam Focal and Systemic Immune Responses to QPX Infection Revealed by RNA-Seq Technology.”</span> <em>BMC Genomics</em> 17 (1): 1–22. <a href="https://doi.org/10.1186/s12864-016-2493-9">https://doi.org/10.1186/s12864-016-2493-9</a>.
</div>
<div id="ref-washingtonseagrant2015shellfish" class="csl-entry" role="listitem">
Washington Sea Grant. 2015. <em>Shellfish Aquaculture in Washington State</em>. <a href="https://wsg.washington.edu/shellfish-aquaculture" class="uri">Https://wsg.washington.edu/shellfish-aquaculture</a>.
</div>
<div id="ref-wdfw2023geoduck" class="csl-entry" role="listitem">
WDFW. 2023. <em>Geoduck Clam (Panopea Generosa)</em>. <a href="https://wdfw.wa.gov/species-habitats/species/panopea-generosa" class="uri">Https://wdfw.wa.gov/species-habitats/species/panopea-generosa</a>; Washington Department of Fish; Wildlife.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/robertslab\.github\.io\/current-findings\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Roberts Lab</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Not peer reviewed unless explicitly stated.</p>
</div>
  </div>
</footer>




</body></html>