<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Steven Roberts">
<meta name="author" content="Mackenzie Gavery">
<meta name="dcterms.date" content="2026-06-17">
<meta name="description" content="First single-cell RNA-seq reference for geoduck: four gastrula replicates integrate into a continuous landscape with nascent ciliary, neural, muscle, and ECM lineage programs.">

<title>A Single-Cell Transcriptomic Reference of the Geoduck (Panopea generosa) Gastrula – Current Findings</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/logo.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f3a7e4420bdcbdb5f5332fa4f27636c7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/logo.svg" alt="Current Findings logo" class="navbar-logo light-content">
    <img src="../../assets/logo.svg" alt="Current Findings logo" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Current Findings</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../reports.html"> 
<span class="menu-text">Reports</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/RobertsLab/current-findings"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background-and-summary" id="toc-background-and-summary" class="nav-link active" data-scroll-target="#background-and-summary"><span class="header-section-number">1</span> Background and Summary</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">2</span> Methods</a>
  <ul class="collapse">
  <li><a href="#sample-design-and-sequencing" id="toc-sample-design-and-sequencing" class="nav-link" data-scroll-target="#sample-design-and-sequencing"><span class="header-section-number">2.1</span> Sample design and sequencing</a></li>
  <li><a href="#quality-control-and-integration" id="toc-quality-control-and-integration" class="nav-link" data-scroll-target="#quality-control-and-integration"><span class="header-section-number">2.2</span> Quality control and integration</a></li>
  <li><a href="#trajectory-analysis" id="toc-trajectory-analysis" class="nav-link" data-scroll-target="#trajectory-analysis"><span class="header-section-number">2.3</span> Trajectory analysis</a></li>
  <li><a href="#functional-and-cell-state-annotation" id="toc-functional-and-cell-state-annotation" class="nav-link" data-scroll-target="#functional-and-cell-state-annotation"><span class="header-section-number">2.4</span> Functional and cell-state annotation</a></li>
  </ul></li>
  <li><a href="#sec-data-records" id="toc-sec-data-records" class="nav-link" data-scroll-target="#sec-data-records"><span class="header-section-number">3</span> Data Records</a></li>
  <li><a href="#technical-validation" id="toc-technical-validation" class="nav-link" data-scroll-target="#technical-validation"><span class="header-section-number">4</span> Technical Validation</a>
  <ul class="collapse">
  <li><a href="#library-quality-and-consistency" id="toc-library-quality-and-consistency" class="nav-link" data-scroll-target="#library-quality-and-consistency"><span class="header-section-number">4.1</span> Library quality and consistency</a></li>
  <li><a href="#integration-removes-the-depth-confound" id="toc-integration-removes-the-depth-confound" class="nav-link" data-scroll-target="#integration-removes-the-depth-confound"><span class="header-section-number">4.2</span> Integration removes the depth confound</a></li>
  <li><a href="#a-continuous-landscape-not-discrete-cell-types" id="toc-a-continuous-landscape-not-discrete-cell-types" class="nav-link" data-scroll-target="#a-continuous-landscape-not-discrete-cell-types"><span class="header-section-number">4.3</span> A continuous landscape, not discrete cell types</a></li>
  <li><a href="#no-single-stage-trajectory" id="toc-no-single-stage-trajectory" class="nav-link" data-scroll-target="#no-single-stage-trajectory"><span class="header-section-number">4.4</span> No single-stage trajectory</a></li>
  <li><a href="#nascent-lineage-programs-along-the-continuum" id="toc-nascent-lineage-programs-along-the-continuum" class="nav-link" data-scroll-target="#nascent-lineage-programs-along-the-continuum"><span class="header-section-number">4.5</span> Nascent lineage programs along the continuum</a></li>
  </ul></li>
  <li><a href="#usage-notes" id="toc-usage-notes" class="nav-link" data-scroll-target="#usage-notes"><span class="header-section-number">5</span> Usage Notes</a></li>
  <li><a href="#suggested-citation" id="toc-suggested-citation" class="nav-link" data-scroll-target="#suggested-citation"><span class="header-section-number">6</span> Suggested citation</a></li>
  <li><a href="#version-history" id="toc-version-history" class="nav-link" data-scroll-target="#version-history"><span class="header-section-number">7</span> Version history</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Single-Cell Transcriptomic Reference of the Geoduck (<em>Panopea generosa</em>) Gastrula</h1>
<p class="subtitle lead">A short non-peer-reviewed scientific report</p>
  <div class="quarto-categories">
    <div class="quarto-category">single-cell</div>
    <div class="quarto-category">transcriptomics</div>
    <div class="quarto-category">development</div>
    <div class="quarto-category">aquaculture</div>
    <div class="quarto-category">geoduck</div>
    <div class="quarto-category">data-descriptor</div>
  </div>
  </div>

<div>
  <div class="description">
    First single-cell RNA-seq reference for geoduck: four gastrula replicates integrate into a continuous landscape with nascent ciliary, neural, muscle, and ECM lineage programs.
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Steven Roberts </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Washington
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Mackenzie Gavery </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            NOAA
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 17, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">June 17, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Status
</div>
</div>
<div class="callout-body-container callout-body">
<p>This report is a Roberts Lab working manuscript. It has not been peer reviewed.</p>
<p>It is shared to make small scientific efforts, preliminary analyses, technical observations, and exploratory work openly available.</p>
<p><a href="https://robertslab.github.io/resources/Agentic-Coding-Tools/#five-level-rubric"><img alt="AI Use Level 3: AI-supported analysis or interpretation" src="https://img.shields.io/badge/AI%20Use-Level%203%20Analysis%2FInterpretation-orange"></a></p>
</div>
</div>
<section id="background-and-summary" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="background-and-summary"><span class="header-section-number">1</span> Background and Summary</h2>
<p>The Pacific geoduck (<em>Panopea generosa</em>) is a long-lived, economically important burrowing clam and a growing focus of aquaculture in the Pacific Northwest. Despite a published genome assembly and annotation, no single-cell transcriptomic data have been available for the species, leaving the cellular composition of its development uncharacterized.</p>
<p>Here we describe a single-cell RNA-sequencing (scRNA-seq) dataset of geoduck gastrula-stage embryos: four separate 10x Genomics libraries (biological replicates of a single developmental stage), processed with Cell Ranger against the <em>P. generosa</em> genome. After uniform quality control and batch integration, the dataset comprises <strong>10,481 high-quality cells</strong> profiled across a shared 34,947-gene reference.</p>
<p>The cells form a <strong>continuous transcriptional landscape</strong> rather than discrete, well-separated cell-type clusters, and no single-stage developmental trajectory is recoverable — the expected signature of a gastrula in which lineage specification is underway but incomplete. Importantly, the continuum is not featureless: once genes are functionally annotated, clusters along it show clear, biologically coherent enrichment for the major embryonic lineage programs — <strong>ciliary/flagellar, neural/ectoderm, muscle/contractile, extracellular-matrix (ECM)/structural, cell-cycle, and biosynthetic (ribosomal)</strong>. Individual cells co-express these programs (graded, not committed), while the cluster-level program structure is strong and interpretable.</p>
<p>To our knowledge this is the first single-cell transcriptomic reference for geoduck. We release it as a resource — raw matrices, an integrated and annotated <code>AnnData</code> object, candidate cell-state marker tables, and interactive Loupe browser files — to support comparative molluscan development and aquaculture genomics. The principal limitations (modest sequencing depth and a single stage) are stated openly and motivate the candidate, signature-based framing of the cell states.</p>
</section>
<section id="methods" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="methods"><span class="header-section-number">2</span> Methods</h2>
<section id="sample-design-and-sequencing" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="sample-design-and-sequencing"><span class="header-section-number">2.1</span> Sample design and sequencing</h3>
<p>Four libraries (G1–G4) were prepared from dissociated cells of geoduck gastrula-stage embryos as <strong>biological replicates of a single stage</strong> (not a developmental time series). Libraries were sequenced and processed with 10x Genomics Cell Ranger <code>count</code> <span class="citation" data-cites="zheng201710x">(<a href="#ref-zheng201710x" role="doc-biblioref"><span class="nocase">Zheng et al.</span> 2017</a>)</span> against the <em>P. generosa</em> genome (<code>Geoduck_mkref_genome</code> reference; 34,947 gene models, <code>PGEN_*</code> identifiers) with <code>--include-introns</code> to capture pre-mRNA reads, appropriate for a non-model invertebrate with a sparse annotation.</p>
<p>Sequencing depth differed substantially between replicates: G3 and G4 received roughly 2–3× the reads of G1 and G2 (Number of Reads 43.4–135.5 M; mean reads/cell 15,332–39,226), which is accounted for in QC below.</p>
</section>
<section id="quality-control-and-integration" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="quality-control-and-integration"><span class="header-section-number">2.2</span> Quality control and integration</h3>
<p>Filtered feature–barcode matrices from all four samples were merged into a single object with sample-prefixed barcodes. To remove a depth-driven low-count tail present only in the shallower samples (G1/G2), <strong>uniform</strong> thresholds were applied across all replicates: ≥250 genes/cell, ≥500 UMI/cell, and genes detected in ≥3 cells. This retained 10,481 of 12,305 cells (85.2%) and 19,324 genes; removed cells came almost entirely from G1 (31%) and G2 (33%), equalizing the per-replicate quality floor.</p>
<p>Counts were normalized (counts-per-10,000, log1p), and 2,000 batch-aware highly-variable genes were selected. After scaling and PCA (50 components), replicate batch effects were removed with <strong>Harmony</strong> <span class="citation" data-cites="korsunsky2019harmony">(<a href="#ref-korsunsky2019harmony" role="doc-biblioref">Korsunsky et al. 2019</a>)</span> over the sample variable. Because G1–G4 are biological replicates, integrating over sample is the appropriate choice. A neighbor graph and UMAP were computed on the Harmony-corrected space, and <strong>Leiden</strong> clustering <span class="citation" data-cites="traag2019louvain">(<a href="#ref-traag2019louvain" role="doc-biblioref">Traag et al. 2019</a>)</span> was run across resolutions 0.1–1.0. Analyses used Scanpy <span class="citation" data-cites="wolf2018scanpy">(<a href="#ref-wolf2018scanpy" role="doc-biblioref">Wolf et al. 2018</a>)</span>.</p>
</section>
<section id="trajectory-analysis" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="trajectory-analysis"><span class="header-section-number">2.3</span> Trajectory analysis</h3>
<p>Developmental-continuum structure was tested with PAGA <span class="citation" data-cites="wolf2019paga">(<a href="#ref-wolf2019paga" role="doc-biblioref">Wolf et al. 2019</a>)</span> and diffusion pseudotime on the integrated object (after removing 23 G1-specific outlier cells).</p>
</section>
<section id="functional-and-cell-state-annotation" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="functional-and-cell-state-annotation"><span class="header-section-number">2.4</span> Functional and cell-state annotation</h3>
<p><code>PGEN</code> gene identifiers were joined to the <em>P. generosa</em> gene-annotation mapping table (UniProt accession, gene symbol, description, GO IDs; <code>20220419-pgen-gene-accessions-gene_id-gene_name-gene_description-alt_gene_description-go_ids.tab</code>). Per-cluster markers were computed with a Wilcoxon rank-sum test and annotated with this table. Six curated lineage-program gene sets (ciliary/flagellar, cell cycle/mitosis, neural/ectoderm, muscle/contractile, ECM/structural, ribosome/translation; 207–526 genes each) were assembled from gene descriptions/symbols/GO terms and scored per cell with <code>scanpy.tl.score_genes</code>. Program scores were averaged per cluster and z-scored across clusters.</p>
</section>
</section>
<section id="sec-data-records" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sec-data-records"><span class="header-section-number">3</span> Data Records</h2>
<p>The release comprises processed single-cell objects, annotation tables, and figures. Counts in <code>.X</code> are raw integers; a log-normalized matrix is stored in <code>.raw</code>, and raw counts are also retained in <code>.layers['counts']</code>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>File</th>
<th>Contents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>geoduck_merged_filtered.h5ad</code></td>
<td>Raw merged matrix, 12,305 cells × 34,947 genes, sample labels</td>
</tr>
<tr class="even">
<td><code>geoduck_integrated.h5ad</code></td>
<td>QC’d (10,481 cells), Harmony-integrated; <code>leiden_*</code> res 0.1–1.0; functional annotation in <code>.var</code>; program scores and <code>top_program</code> in <code>.obs</code></td>
</tr>
<tr class="odd">
<td><code>geoduck_trajectory.h5ad</code></td>
<td>10,458 cells (G1 outliers removed); PAGA, diffusion pseudotime, diffmap</td>
</tr>
<tr class="even">
<td><code>cluster_markers_annotated.csv</code></td>
<td>Top-15 markers per cluster with symbol, description, log-fold-change, adjusted p-value</td>
</tr>
<tr class="odd">
<td><code>program_scores_by_cluster.csv</code></td>
<td>Mean lineage-program score per cluster</td>
</tr>
<tr class="even">
<td>Per-sample Cell Ranger <code>outs/</code></td>
<td>Filtered/raw matrices, BAMs, <code>metrics_summary.csv</code>, <code>web_summary.html</code>, <code>cloupe.cloupe</code></td>
</tr>
</tbody>
</table>
</section>
<section id="technical-validation" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="technical-validation"><span class="header-section-number">4</span> Technical Validation</h2>
<section id="library-quality-and-consistency" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="library-quality-and-consistency"><span class="header-section-number">4.1</span> Library quality and consistency</h3>
<p>All four libraries align to the same reference and share nearly identical top-expressed genes, indicating consistent chemistry with no per-sample technical artifact dominating. The most abundant gene accounts for only ~0.75% of UMIs in every sample (no rRNA/mitochondrial contamination). Mapping rates were modest across samples (~42% confidently to genome, ~23% to transcriptome) — typical for a non-model invertebrate with an imperfect annotation.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 16%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Sample</th>
<th style="text-align: right;">Cells</th>
<th style="text-align: right;">Median UMI/cell</th>
<th style="text-align: right;">Median genes/cell</th>
<th style="text-align: right;">Total reads</th>
<th style="text-align: right;">Genes detected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>G1</td>
<td style="text-align: right;">2,912</td>
<td style="text-align: right;">724</td>
<td style="text-align: right;">551</td>
<td style="text-align: right;">48.1 M</td>
<td style="text-align: right;">18,050</td>
</tr>
<tr class="even">
<td>G2</td>
<td style="text-align: right;">2,832</td>
<td style="text-align: right;">714</td>
<td style="text-align: right;">547</td>
<td style="text-align: right;">43.4 M</td>
<td style="text-align: right;">17,738</td>
</tr>
<tr class="odd">
<td>G3</td>
<td style="text-align: right;">3,107</td>
<td style="text-align: right;">1,467</td>
<td style="text-align: right;">953</td>
<td style="text-align: right;">103.1 M</td>
<td style="text-align: right;">20,063</td>
</tr>
<tr class="even">
<td>G4</td>
<td style="text-align: right;">3,454</td>
<td style="text-align: right;">1,649</td>
<td style="text-align: right;">1,038</td>
<td style="text-align: right;">135.5 M</td>
<td style="text-align: right;">21,004</td>
</tr>
</tbody>
</table>
</section>
<section id="integration-removes-the-depth-confound" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="integration-removes-the-depth-confound"><span class="header-section-number">4.2</span> Integration removes the depth confound</h3>
<p>Before integration, replicate centroids showed an ordered drift in PCA space (G1≈G2 → G3 → G4) tracking the G1/G2-versus-G3/G4 sequencing-depth difference. Since the libraries are replicates, this is a nuisance rather than biology; Harmony removed it, and the integrated UMAP shows the four replicates thoroughly intermixed (<a href="#fig-integration" class="quarto-xref">Figure&nbsp;2</a>).</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-preint" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-preint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/umap_preHarmony_sample.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-preint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Before integration: replicates drift apart, tracking sequencing depth.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-integration" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-integration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/umap_sample.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-integration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: After Harmony integration: the four replicates are thoroughly intermixed.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="a-continuous-landscape-not-discrete-cell-types" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="a-continuous-landscape-not-discrete-cell-types"><span class="header-section-number">4.3</span> A continuous landscape, not discrete cell types</h3>
<p>Leiden clustering across resolutions does not yield robustly separable clusters: below resolution 0.4 all cells collapse to a single cluster, and at resolution ≥0.6 the silhouette score on the integrated space is negative — clusters partition a continuum rather than separating discrete islands. At resolution 0.4 the dominant cluster holds 10,458 of 10,481 cells (99.8%); the only structure that splits off is three tiny G1-specific outlier specks (4, 5, and 14 cells), which were removed from downstream analysis (<a href="#fig-res04" class="quarto-xref">Figure&nbsp;3</a>).</p>
<div id="fig-res04" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-res04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/umap_res0.4.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-res04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Leiden clustering at resolution 0.4: one dominant cluster (blue) plus three tiny G1-specific outlier specks at the periphery.
</figcaption>
</figure>
</div>
</section>
<section id="no-single-stage-trajectory" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="no-single-stage-trajectory"><span class="header-section-number">4.4</span> No single-stage trajectory</h3>
<p>PAGA and diffusion pseudotime independently indicate no trajectory: the diffusion spectrum is flat (no spectral gap after the trivial first eigenvalue), the PAGA graph is a fully-connected mesh (all 55 cluster pairs strongly connected; median connectivity 0.74), and pseudotime shows no gradient and is flat across replicates (<a href="#fig-paga" class="quarto-xref">Figure&nbsp;4</a>, <a href="#fig-pseudotime" class="quarto-xref">Figure&nbsp;5</a>). This is expected: trajectory inference requires cells spanning developmental time, which a single stage does not provide.</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-paga" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-paga-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/paga_geoduck.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-paga-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: PAGA abstraction: a complete mesh, indicating one continuously connected mass rather than a branched topology.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-pseudotime" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pseudotime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/umap_pseudotime.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pseudotime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Diffusion pseudotime shows no gradient across the manifold.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="nascent-lineage-programs-along-the-continuum" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="nascent-lineage-programs-along-the-continuum"><span class="header-section-number">4.5</span> Nascent lineage programs along the continuum</h3>
<p>Functional annotation covered <strong>11,549 of 19,324 expressed genes (59.8%)</strong>. Top cluster markers include recognizable, conserved cell-state genes — ciliary/IFT genes (<code>cfap36</code>, <code>Ift88</code>, <code>KIF3A</code>, axonemal dynein assembly factors), neural/ectoderm transcription factors (<code>sox3</code>, <code>TFAP2A</code>), and cell-cycle genes (<code>cyclin-B</code>, <code>Cdt1</code>, <code>Aurka</code>, <code>ttk</code>).</p>
<p>Scoring the six curated lineage programs shows that <strong>clusters are strongly distinguished by program</strong> (per-program enrichment spread 3.4–4.9 z-units across clusters; <a href="#fig-heatmap" class="quarto-xref">Figure&nbsp;6</a>), even though the programs are spatially diffuse on the UMAP (<a href="#fig-progscores" class="quarto-xref">Figure&nbsp;7</a>). Per-cell specialization is weak (median top1–top2 program-score margin = 0.58 z), i.e.&nbsp;individual cells co-express multiple programs.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Program</th>
<th style="text-align: right;">Genes</th>
<th>Strongly enriched clusters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ciliary/flagellar</td>
<td style="text-align: right;">526</td>
<td>5, 13, 26</td>
</tr>
<tr class="even">
<td>Cell cycle/mitosis</td>
<td style="text-align: right;">494</td>
<td>10, 24</td>
</tr>
<tr class="odd">
<td>Neural/ectoderm</td>
<td style="text-align: right;">429</td>
<td>2, 8, 17, 20</td>
</tr>
<tr class="even">
<td>Muscle/contractile</td>
<td style="text-align: right;">254</td>
<td>3, 19, 22, 25</td>
</tr>
<tr class="odd">
<td>ECM/structural</td>
<td style="text-align: right;">270</td>
<td>11, 12, 14, 16, 21, 23</td>
</tr>
<tr class="even">
<td>Ribosome/translation</td>
<td style="text-align: right;">207</td>
<td>0, 1, 4, 9, 18</td>
</tr>
</tbody>
</table>
<div id="fig-heatmap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/program_heatmap.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Lineage-program enrichment by cluster (z-score across clusters). Dots mark each cluster’s dominant program. Clusters are clearly distinguished by program despite weak per-cell specialization.
</figcaption>
</figure>
</div>
<div id="fig-progscores" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-progscores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/umap_program_scores.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-progscores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Per-cell lineage-program scores on the UMAP. Programs are detectable but spatially diffuse, consistent with graded rather than committed specialization.
</figcaption>
</figure>
</div>
<p>Together these results indicate that the major embryonic lineage programs are already detectable and cluster-organized at the gastrula stage, but not yet resolved into discrete, committed cell-type territories — the expected hallmark of mid-gastrulation.</p>
</section>
</section>
<section id="usage-notes" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="usage-notes"><span class="header-section-number">5</span> Usage Notes</h2>
<p>Program- and cluster-level assignments are <strong>candidate, signature-based</strong> identities and warrant orthogonal validation (e.g.&nbsp;whole-mount HCR/in situ hybridization of representative ciliary, neural, and muscle markers). Two characteristics should guide reuse: (i) the dataset is a single developmental stage, so it cannot support developmental-trajectory reconstruction on its own; and (ii) sequencing depth is modest (median ~550–1,650 UMI/cell), which limits resolution of fine sub-states. Deeper sequencing and additional stages would address these directly. The annotated <code>geoduck_integrated.h5ad</code> is the recommended entry point; the Loupe (<code>cloupe.cloupe</code>) files allow interactive browsing without a Python/R environment.</p>
</section>
<section id="suggested-citation" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="suggested-citation"><span class="header-section-number">6</span> Suggested citation</h2>
<p>Roberts, S. B. 2026. <em>A Single-Cell Transcriptomic Reference of the Geoduck (Panopea generosa) Gastrula</em>. Current Findings. Available at: https://robertslab.github.io/current-findings/reports/geoduck-gastrula-scrnaseq/</p>
</section>
<section id="version-history" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="version-history"><span class="header-section-number">7</span> Version history</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Version</th>
<th>Date</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.1</td>
<td>2026-06-17</td>
<td>Drafted from REPORT.md analysis report</td>
</tr>
</tbody>
</table>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-korsunsky2019harmony" class="csl-entry" role="listitem">
Korsunsky, Ilya, Nghia Millard, Jean Fan, et al. 2019. <span>“Fast, Sensitive and Accurate Integration of Single-Cell Data with Harmony.”</span> <em>Nature Methods</em> 16 (12): 1289–96. <a href="https://doi.org/10.1038/s41592-019-0619-0">https://doi.org/10.1038/s41592-019-0619-0</a>.
</div>
<div id="ref-traag2019louvain" class="csl-entry" role="listitem">
Traag, Vincent A., Ludo Waltman, and Nees Jan van Eck. 2019. <span>“From Louvain to Leiden: Guaranteeing Well-Connected Communities.”</span> <em>Scientific Reports</em> 9 (1): 5233. <a href="https://doi.org/10.1038/s41598-019-41695-z">https://doi.org/10.1038/s41598-019-41695-z</a>.
</div>
<div id="ref-wolf2018scanpy" class="csl-entry" role="listitem">
Wolf, F. Alexander, Philipp Angerer, and Fabian J. Theis. 2018. <span>“SCANPY: Large-Scale Single-Cell Gene Expression Data Analysis.”</span> <em>Genome Biology</em> 19 (1): 15. <a href="https://doi.org/10.1186/s13059-017-1382-0">https://doi.org/10.1186/s13059-017-1382-0</a>.
</div>
<div id="ref-wolf2019paga" class="csl-entry" role="listitem">
Wolf, F. Alexander, Fiona K. Hamey, Mireya Plass, et al. 2019. <span>“PAGA: Graph Abstraction Reconciles Clustering with Trajectory Inference Through a Topology Preserving Map of Single Cells.”</span> <em>Genome Biology</em> 20 (1): 59. <a href="https://doi.org/10.1186/s13059-019-1663-x">https://doi.org/10.1186/s13059-019-1663-x</a>.
</div>
<div id="ref-zheng201710x" class="csl-entry" role="listitem">
<span class="nocase">Zheng, Grace X. Y., Jessica M. Terry, Phillip Belgrader, et al.</span> 2017. <span>“Massively Parallel Digital Transcriptional Profiling of Single Cells.”</span> <em>Nature Communications</em> 8: 14049. <a href="https://doi.org/10.1038/ncomms14049">https://doi.org/10.1038/ncomms14049</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/robertslab\.github\.io\/current-findings\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Roberts Lab</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Not peer reviewed unless explicitly stated.</p>
</div>
  </div>
</footer>




</body></html>