<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Steven Roberts">
<meta name="dcterms.date" content="2026-06-17">
<meta name="description" content="Synthesis of 11 studies showing Ostrea lurida populations differ heritably across genetics, phenotype, physiology, and methylation—with implications for restoration.">

<title>Fundamental Differences Among Olympia Oyster Populations – Current Findings</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/logo.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7af0013c55bc89f24c80d2b634244bd9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/logo.svg" alt="Current Findings logo" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Current Findings</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../reports.html"> 
<span class="menu-text">Reports</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/RobertsLab/current-findings"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary"><span class="header-section-number">1</span> Executive Summary</a></li>
  <li><a href="#background-and-scope" id="toc-background-and-scope" class="nav-link" data-scroll-target="#background-and-scope"><span class="header-section-number">2</span> Background and Scope</a></li>
  <li><a href="#genetic-differentiation-structure-across-two-scales" id="toc-genetic-differentiation-structure-across-two-scales" class="nav-link" data-scroll-target="#genetic-differentiation-structure-across-two-scales"><span class="header-section-number">3</span> Genetic Differentiation: Structure Across Two Scales</a>
  <ul class="collapse">
  <li><a href="#rangewide-structure-and-biogeographic-barriers" id="toc-rangewide-structure-and-biogeographic-barriers" class="nav-link" data-scroll-target="#rangewide-structure-and-biogeographic-barriers"><span class="header-section-number">3.1</span> Rangewide structure and biogeographic barriers</a></li>
  <li><a href="#fine-scale-structure-within-puget-sound" id="toc-fine-scale-structure-within-puget-sound" class="nav-link" data-scroll-target="#fine-scale-structure-within-puget-sound"><span class="header-section-number">3.2</span> Fine-scale structure within Puget Sound</a></li>
  </ul></li>
  <li><a href="#phenotypic-divergence-heritable-trade-offs-among-three-puget-sound-populations" id="toc-phenotypic-divergence-heritable-trade-offs-among-three-puget-sound-populations" class="nav-link" data-scroll-target="#phenotypic-divergence-heritable-trade-offs-among-three-puget-sound-populations"><span class="header-section-number">4</span> Phenotypic Divergence: Heritable Trade-Offs Among Three Puget Sound Populations</a>
  <ul class="collapse">
  <li><a href="#reciprocal-transplant-heare-2017" id="toc-reciprocal-transplant-heare-2017" class="nav-link" data-scroll-target="#reciprocal-transplant-heare-2017"><span class="header-section-number">4.1</span> Reciprocal transplant (Heare 2017)</a></li>
  <li><a href="#multigenerational-common-garden-silliman-2018" id="toc-multigenerational-common-garden-silliman-2018" class="nav-link" data-scroll-target="#multigenerational-common-garden-silliman-2018"><span class="header-section-number">4.2</span> Multigenerational common garden (Silliman 2018)</a></li>
  </ul></li>
  <li><a href="#physiological-and-molecular-divergence-population-specific-stress-response" id="toc-physiological-and-molecular-divergence-population-specific-stress-response" class="nav-link" data-scroll-target="#physiological-and-molecular-divergence-population-specific-stress-response"><span class="header-section-number">5</span> Physiological and Molecular Divergence: Population-Specific Stress Response</a>
  <ul class="collapse">
  <li><a href="#gene-expression-under-acute-stress-heare-2018" id="toc-gene-expression-under-acute-stress-heare-2018" class="nav-link" data-scroll-target="#gene-expression-under-acute-stress-heare-2018"><span class="header-section-number">5.1</span> Gene expression under acute stress (Heare 2018)</a></li>
  <li><a href="#population-specific-response-to-ocean-acidification-spencer-2023" id="toc-population-specific-response-to-ocean-acidification-spencer-2023" class="nav-link" data-scroll-target="#population-specific-response-to-ocean-acidification-spencer-2023"><span class="header-section-number">5.2</span> Population-specific response to ocean acidification (Spencer 2023)</a></li>
  <li><a href="#reproductive-phenology-and-intergenerational-carryover-spencer-2020-2021" id="toc-reproductive-phenology-and-intergenerational-carryover-spencer-2020-2021" class="nav-link" data-scroll-target="#reproductive-phenology-and-intergenerational-carryover-spencer-2020-2021"><span class="header-section-number">5.3</span> Reproductive phenology and intergenerational carryover (Spencer 2020, 2021)</a></li>
  <li><a href="#early-life-history-and-recruitment-supply-becker-2020" id="toc-early-life-history-and-recruitment-supply-becker-2020" class="nav-link" data-scroll-target="#early-life-history-and-recruitment-supply-becker-2020"><span class="header-section-number">5.4</span> Early life history and recruitment supply (Becker 2020)</a></li>
  </ul></li>
  <li><a href="#epigenetic-divergence-methylation-coupled-to-genotype" id="toc-epigenetic-divergence-methylation-coupled-to-genotype" class="nav-link" data-scroll-target="#epigenetic-divergence-methylation-coupled-to-genotype"><span class="header-section-number">6</span> Epigenetic Divergence: Methylation Coupled to Genotype</a></li>
  <li><a href="#integration-a-coherent-picture-of-population-differentiation" id="toc-integration-a-coherent-picture-of-population-differentiation" class="nav-link" data-scroll-target="#integration-a-coherent-picture-of-population-differentiation"><span class="header-section-number">7</span> Integration: A Coherent Picture of Population Differentiation</a></li>
  <li><a href="#implications-for-restoration-and-aquaculture-practice" id="toc-implications-for-restoration-and-aquaculture-practice" class="nav-link" data-scroll-target="#implications-for-restoration-and-aquaculture-practice"><span class="header-section-number">8</span> Implications for Restoration and Aquaculture Practice</a>
  <ul class="collapse">
  <li><a href="#treat-populations-as-locally-adapted-management-units" id="toc-treat-populations-as-locally-adapted-management-units" class="nav-link" data-scroll-target="#treat-populations-as-locally-adapted-management-units"><span class="header-section-number">8.1</span> Treat populations as locally adapted management units</a></li>
  <li><a href="#source-broodstock-locally-and-avoid-homogenizing-transfers" id="toc-source-broodstock-locally-and-avoid-homogenizing-transfers" class="nav-link" data-scroll-target="#source-broodstock-locally-and-avoid-homogenizing-transfers"><span class="header-section-number">8.2</span> Source broodstock locally and avoid homogenizing transfers</a></li>
  <li><a href="#protect-genetic-diversity-in-the-hatchery" id="toc-protect-genetic-diversity-in-the-hatchery" class="nav-link" data-scroll-target="#protect-genetic-diversity-in-the-hatchery"><span class="header-section-number">8.3</span> Protect genetic diversity in the hatchery</a></li>
  <li><a href="#match-source-population-to-restoration-goal-and-future-climate" id="toc-match-source-population-to-restoration-goal-and-future-climate" class="nav-link" data-scroll-target="#match-source-population-to-restoration-goal-and-future-climate"><span class="header-section-number">8.4</span> Match source population to restoration goal and future climate</a></li>
  <li><a href="#leverage-parental-conditioning-carryover-effects" id="toc-leverage-parental-conditioning-carryover-effects" class="nav-link" data-scroll-target="#leverage-parental-conditioning-carryover-effects"><span class="header-section-number">8.5</span> Leverage parental conditioning (carryover effects)</a></li>
  <li><a href="#optimize-outplant-siting-and-timing" id="toc-optimize-outplant-siting-and-timing" class="nav-link" data-scroll-target="#optimize-outplant-siting-and-timing"><span class="header-section-number">8.6</span> Optimize outplant siting and timing</a></li>
  </ul></li>
  <li><a href="#next-steps-in-research" id="toc-next-steps-in-research" class="nav-link" data-scroll-target="#next-steps-in-research"><span class="header-section-number">9</span> Next Steps in Research</a>
  <ul class="collapse">
  <li><a href="#link-adaptive-genotype-to-phenotype" id="toc-link-adaptive-genotype-to-phenotype" class="nav-link" data-scroll-target="#link-adaptive-genotype-to-phenotype"><span class="header-section-number">9.1</span> Link adaptive genotype to phenotype</a></li>
  <li><a href="#disentangle-genetic-epigenetic-and-carryover-contributions" id="toc-disentangle-genetic-epigenetic-and-carryover-contributions" class="nav-link" data-scroll-target="#disentangle-genetic-epigenetic-and-carryover-contributions"><span class="header-section-number">9.2</span> Disentangle genetic, epigenetic, and carryover contributions</a></li>
  <li><a href="#extend-physiological-testing-across-the-full-range-and-multiple-stressors" id="toc-extend-physiological-testing-across-the-full-range-and-multiple-stressors" class="nav-link" data-scroll-target="#extend-physiological-testing-across-the-full-range-and-multiple-stressors"><span class="header-section-number">9.3</span> Extend physiological testing across the full range and multiple stressors</a></li>
  <li><a href="#quantify-real-world-larval-dispersal-and-connectivity" id="toc-quantify-real-world-larval-dispersal-and-connectivity" class="nav-link" data-scroll-target="#quantify-real-world-larval-dispersal-and-connectivity"><span class="header-section-number">9.4</span> Quantify real-world larval dispersal and connectivity</a></li>
  <li><a href="#build-a-genomic-monitoring-and-broodstock-management-toolkit" id="toc-build-a-genomic-monitoring-and-broodstock-management-toolkit" class="nav-link" data-scroll-target="#build-a-genomic-monitoring-and-broodstock-management-toolkit"><span class="header-section-number">9.5</span> Build a genomic monitoring and broodstock-management toolkit</a></li>
  <li><a href="#test-conditioning-and-assisted-adaptation-strategies-operationally" id="toc-test-conditioning-and-assisted-adaptation-strategies-operationally" class="nav-link" data-scroll-target="#test-conditioning-and-assisted-adaptation-strategies-operationally"><span class="header-section-number">9.6</span> Test conditioning and assisted-adaptation strategies operationally</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">10</span> Conclusion</a>
  <ul class="collapse">
  <li><a href="#suggested-citation" id="toc-suggested-citation" class="nav-link" data-scroll-target="#suggested-citation"><span class="header-section-number">10.1</span> Suggested citation</a></li>
  <li><a href="#version-history" id="toc-version-history" class="nav-link" data-scroll-target="#version-history"><span class="header-section-number">10.2</span> Version history</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fundamental Differences Among Olympia Oyster Populations</h1>
<p class="subtitle lead">An integrated synthesis of genetic, phenotypic, physiological, and epigenetic divergence in <em>Ostrea lurida</em></p>
  <div class="quarto-categories">
    <div class="quarto-category">oysters</div>
    <div class="quarto-category">population-structure</div>
    <div class="quarto-category">epigenetics</div>
    <div class="quarto-category">genomics</div>
    <div class="quarto-category">restoration</div>
    <div class="quarto-category">aquaculture</div>
  </div>
  </div>

<div>
  <div class="description">
    Synthesis of 11 studies showing Ostrea lurida populations differ heritably across genetics, phenotype, physiology, and methylation—with implications for restoration.
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Steven Roberts </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Washington
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 17, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">June 17, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Status
</div>
</div>
<div class="callout-body-container callout-body">
<p>This report is a Roberts Lab working manuscript. It has not been peer reviewed.</p>
<p>It is shared to make small scientific efforts, preliminary analyses, technical observations, and exploratory work openly available.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Scope
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is an integrated synthesis of 11 primary studies from the <em>Ostrea lurida</em> literature collection, addressing how—and at what scales—Olympia oyster populations differ, and what those differences mean for restoration and aquaculture.</p>
</div>
</div>
<section id="executive-summary" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Executive Summary</h1>
<p>The Olympia oyster (<em>Ostrea lurida</em>) is the only oyster native to the west coast of North America. Once forming extensive beds from Baja California to central British Columbia, the species was devastated by commercial overharvest in the late nineteenth and early twentieth centuries and today persists at roughly 2–5% of its historic abundance. As restoration has accelerated over the past two decades, a recurring and consequential question has emerged: are <em>O. lurida</em> populations interchangeable, or are they fundamentally different from one another in ways that matter for how they should be managed, bred, and outplanted?</p>
<p>The body of work synthesized here—eleven studies spanning genomics, reciprocal transplants, multigenerational common-garden experiments, reproductive physiology, gene expression, and DNA methylation—answers that question decisively: <strong>Olympia oyster populations are not interchangeable.</strong> They differ at every biological level examined, from neutral and adaptive genetic markers down to the methylome, and crucially these differences manifest as heritable, ecologically relevant phenotypes—growth rate, survival, reproductive timing and output, stress tolerance, and resilience to ocean acidification—that persist when animals are raised together in common conditions for up to four years and two generations.</p>
<p>Two spatial scales of differentiation are evident. At the <strong>rangewide scale</strong>, genome-wide data resolve six phylogeographic regions structured by isolation-by-distance and known marine biogeographic barriers. At the <strong>local (within–Puget Sound) scale</strong>, three populations—Dabob Bay, Oyster Bay, and Fidalgo Bay—display consistent, heritable trade-offs among growth, survival, fecundity, and stress response that recur across independent experiments. These local differences, observed over distances of only tens of kilometers, are the single most important practical finding for restoration: they mean broodstock sourcing decisions carry real fitness consequences, and that mixing or homogenizing stocks risks erasing locally adapted variation that underpins long-term population resilience.</p>
</section>
<section id="background-and-scope" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Background and Scope</h1>
<p><em>O. lurida</em> is an estuarine ecosystem engineer that provides structured habitat, filters suspended sediment, and limits eutrophication. Its life history differs fundamentally from the introduced Pacific oyster (<em>Crassostrea gigas</em>). <em>O. lurida</em> is a rhythmic consecutive (protandric) hermaphrodite that spawns first as male and oscillates between sexes within a season; rather than broadcasting eggs, females retain eggs and capture planktonic sperm, then <strong>brood larvae internally</strong> for roughly 10–14 days before releasing competent D-stage veligers. This brooding life history shortens the effective planktonic dispersal window and creates the potential for reproductive isolation and fine-scale genetic structure—a theme that runs through nearly every paper in this collection.</p>
<p>This synthesis integrates the eleven supplied studies into a single account of how—and at what scales—Olympia oyster populations differ, and what those differences mean for restoration and aquaculture. The studies fall into five complementary lines of evidence, summarized in <a href="#tbl-evidence" class="quarto-xref">Table&nbsp;1</a> and integrated in the sections that follow.</p>
<div id="tbl-evidence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-evidence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The evidence base.
</figcaption>
<div aria-describedby="tbl-evidence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Study</th>
<th>Approach</th>
<th>Scale / populations</th>
<th>Core contribution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation" data-cites="timminsschiffman2013">Timmins-Schiffman et al. (<a href="#ref-timminsschiffman2013" role="doc-biblioref">2013</a>)</span></td>
<td>Larval transcriptome sequencing</td>
<td>Species-level (Puget Sound)</td>
<td>First genomic resource (41,136 contigs); stress/immune genes</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="white2017">White et al. (<a href="#ref-white2017" role="doc-biblioref">2017</a>)</span></td>
<td>Genotype-by-sequencing data descriptor</td>
<td>3 Puget Sound populations</td>
<td>10,363-locus SNP panel; flags stock-mixing risk</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="heare2017">Heare et al. (<a href="#ref-heare2017" role="doc-biblioref">2017</a>)</span></td>
<td>Reciprocal transplant (F1), 4 sites</td>
<td>Dabob, Oyster, Fidalgo</td>
<td>Population differences in survival, growth, brooding</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="silliman2018">K. E. Silliman, Bowyer, and Roberts (<a href="#ref-silliman2018" role="doc-biblioref">2018</a>)</span></td>
<td>Common garden, F1 and F2</td>
<td>Dabob, Oyster, Fidalgo</td>
<td>Trait differences heritable across 2 generations</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="silliman2019">K. Silliman (<a href="#ref-silliman2019" role="doc-biblioref">2019</a>)</span></td>
<td>Rangewide GBS, 13,424 SNPs</td>
<td>Range: S. CA–Vancouver Is.</td>
<td>Six phylogeographic regions; outlier loci</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="heare2018">Heare et al. (<a href="#ref-heare2018" role="doc-biblioref">2018</a>)</span></td>
<td>Gene expression under stress</td>
<td>Dabob, Oyster, Fidalgo</td>
<td>Population-specific molecular stress response</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="becker2020">Becker et al. (<a href="#ref-becker2020" role="doc-biblioref">2020</a>)</span></td>
<td>Field larval/settlement survey</td>
<td>Fidalgo Bay restoration site</td>
<td>Pre-recruitment processes govern local supply</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="spencer2020">Spencer et al. (<a href="#ref-spencer2020" role="doc-biblioref">2020</a>)</span></td>
<td>Winter warming × pCO2, carryover</td>
<td>3 populations + cohort</td>
<td>Intergenerational carryover effects</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="spencer2021">Spencer et al. (<a href="#ref-spencer2021" role="doc-biblioref">2021</a>)</span></td>
<td>Winter warming × food</td>
<td>Central Puget Sound</td>
<td>Reproduction resilient to winter warming</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="spencer2023">Spencer, Roberts, and Silliman (<a href="#ref-spencer2023" role="doc-biblioref">2023</a>)</span></td>
<td>Population-specific OA response</td>
<td>Dabob, Oyster, Fidalgo</td>
<td>Distinct transcriptomic physiotypes</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="silliman2023">K. Silliman et al. (<a href="#ref-silliman2023" role="doc-biblioref">2023</a>)</span></td>
<td>Integrated genome + methylome</td>
<td>2 populations</td>
<td>Genetic–epigenetic coupling (~27%)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="genetic-differentiation-structure-across-two-scales" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Genetic Differentiation: Structure Across Two Scales</h1>
<section id="rangewide-structure-and-biogeographic-barriers" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="rangewide-structure-and-biogeographic-barriers"><span class="header-section-number">3.1</span> Rangewide structure and biogeographic barriers</h2>
<p><span class="citation" data-cites="silliman2019">K. Silliman (<a href="#ref-silliman2019" role="doc-biblioref">2019</a>)</span> provided the first modern, genome-wide test of rangewide structure, genotyping oysters from southern California to Vancouver Island at 13,424 SNPs and analyzing putatively neutral and outlier loci separately. The data reject the null model of panmixia. Instead, allele frequencies follow a strong <strong>isolation-by-distance</strong> gradient—latitude explained roughly 83–86% of variation along the first principal component—overlaid on <strong>six distinct phylogeographic regions</strong>: Northwest British Columbia, Puget Sound + southern BC, Willapa Bay, Oregon, Northern California, and Southern California.</p>
<p>Regional boundaries coincide with recognized marine biogeographic barriers—<strong>Cape Mendocino, Monterey Bay, and the currents around Cape Flattery</strong>—where reduced gene flow (resolved as discrete barriers in EEMS analyses) interrupts the otherwise smooth latitudinal cline. Genetic diversity is highest in the Southern California region, consistent with northward post-glacial recolonization and bottlenecks in the north. Neutral markers resolved finer structure than outlier loci, but both recovered the same regional architecture. The outlier loci under putative selection were annotated to genes for developmental regulation, sensory processing, energy metabolism, immune response, and muscle contraction—candidate targets of local adaptation and useful markers for future genetic monitoring.</p>
<p>This rangewide picture confirms and extends earlier mitochondrial phylogeography (a break north of Willapa Bay; the <em>O. lurida</em> / <em>O. conchaphila</em> species boundary to the south) and an unpublished microsatellite dissertation, but with far greater resolution. The central message is that <em>O. lurida</em> is <strong>regionally structured, not panmictic</strong>, despite a planktonic larval phase—exactly the pattern expected when brooding limits effective dispersal and selective gradients are steep.</p>
</section>
<section id="fine-scale-structure-within-puget-sound" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="fine-scale-structure-within-puget-sound"><span class="header-section-number">3.2</span> Fine-scale structure within Puget Sound</h2>
<p><span class="citation" data-cites="heare2017">Heare et al. (<a href="#ref-heare2017" role="doc-biblioref">2017</a>)</span> supplied the first peer-reviewed evidence of structure at the within–Puget Sound scale, and <span class="citation" data-cites="white2017">White et al. (<a href="#ref-white2017" role="doc-biblioref">2017</a>)</span> released the underlying genotype-by-sequencing resource: a 10,363-locus SNP panel for three geographically and environmentally distinct bays—<strong>Fidalgo Bay</strong> (northern, cold, Strait of Juan de Fuca influence), <strong>Dabob Bay</strong> (a stratified, long-retention fjord arm of Hood Canal), and <strong>Oyster Bay</strong> (south Sound, warm, productive, historically abundant). The brooding life history, the authors argued, plausibly generates reproductive isolation even over these short distances—and the genetic data, combined with the phenotypic results below, bear that out.</p>
<p><span class="citation" data-cites="white2017">White et al. (<a href="#ref-white2017" role="doc-biblioref">2017</a>)</span> framed the practical stakes precisely: hatchery production typically uses few broodstock to generate large numbers of outplants, which <strong>reduces effective population size and genetic diversity in the very populations being restored</strong>. Without stock-structure information, well-intentioned transfers of animals among bays can homogenize or erase the genetic differences that distinguish them—leaving restored populations genetically depauperate and less resilient even as census numbers rise.</p>
</section>
</section>
<section id="phenotypic-divergence-heritable-trade-offs-among-three-puget-sound-populations" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Phenotypic Divergence: Heritable Trade-Offs Among Three Puget Sound Populations</h1>
<p>The most thoroughly documented differences in this literature are the heritable life-history trade-offs among Dabob Bay, Oyster Bay, and Fidalgo Bay. Two independent experimental designs—a field reciprocal transplant <span class="citation" data-cites="heare2017">(<a href="#ref-heare2017" role="doc-biblioref">Heare et al. 2017</a>)</span> and a two-generation common garden <span class="citation" data-cites="silliman2018">(<a href="#ref-silliman2018" role="doc-biblioref">K. E. Silliman, Bowyer, and Roberts 2018</a>)</span>—converge on the same population physiotypes, and later physiological work <span class="citation" data-cites="spencer2023">(<a href="#ref-spencer2023" role="doc-biblioref">Spencer, Roberts, and Silliman 2023</a>)</span> reproduces them yet again.</p>
<section id="reciprocal-transplant-heare-2017" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="reciprocal-transplant-heare-2017"><span class="header-section-number">4.1</span> Reciprocal transplant (Heare 2017)</h2>
<p>First-generation (F1) oysters from each source population were outplanted to four sites spanning the Sound. Performance differed by population in a way that was largely consistent across environments—evidence of intrinsic, population-level differences rather than purely plastic responses to site:</p>
<ul>
<li><strong>Dabob Bay</strong> — highest survival at all sites, but the lowest growth and lowest reproductive activity.</li>
<li><strong>Fidalgo Bay</strong> — fastest growth, but reduced or delayed reproduction; lowest survival in the warm Hood Canal environment.</li>
<li><strong>Oyster Bay</strong> — greatest proportion of brooding females at most sites (highest reproductive effort), with moderate growth and survival.</li>
</ul>
<p>These patterns describe a classic life-history trade-off: populations cannot simultaneously maximize growth, survival, and reproduction, and each bay’s oysters allocate energy differently—Dabob toward survival, Fidalgo toward growth, Oyster Bay toward reproduction.</p>
</section>
<section id="multigenerational-common-garden-silliman-2018" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="multigenerational-common-garden-silliman-2018"><span class="header-section-number">4.2</span> Multigenerational common garden (Silliman 2018)</h2>
<p>A crucial alternative explanation for the transplant results is transgenerational plasticity (TGP)—parental environment shaping offspring phenotype non-genetically. <span class="citation" data-cites="silliman2018">K. E. Silliman, Bowyer, and Roberts (<a href="#ref-silliman2018" role="doc-biblioref">2018</a>)</span> addressed this directly by rearing F1 and F2 oysters from the same three populations under common conditions for up to two generations and measuring reproduction, larval growth, and juvenile growth. The population signatures persisted: Fidalgo oysters again grew fastest (their larvae were 6–8% larger by day 7) yet released the fewest larvae (1.1 million vs.&nbsp;2.7 million for Oyster Bay and 2.4 million for Dabob) and began reproducing latest and most variably. Because these differences held across two laboratory-reared generations, they have a <strong>strongly heritable component that cannot be attributed to plasticity alone</strong>. The fast-growth / delayed-reproduction coupling in Fidalgo is interpreted as a genuine adaptive trade-off.</p>
<div id="tbl-physiotypes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-physiotypes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Convergent population physiotypes across independent studies. The consistency of these rankings across a field transplant, a two-generation common garden, and a multi-year physiological experiment is the strongest possible evidence that the differences are real, heritable, and adaptively meaningful.
</figcaption>
<div aria-describedby="tbl-physiotypes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Population</th>
<th>Growth</th>
<th>Survival</th>
<th>Reproduction / fecundity</th>
<th>Acidification response <span class="citation" data-cites="spencer2023">(<a href="#ref-spencer2023" role="doc-biblioref">Spencer, Roberts, and Silliman 2023</a>)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Dabob Bay</strong></td>
<td>Slowest</td>
<td>Highest</td>
<td>Low–moderate; delayed</td>
<td>Largest transcriptomic response; no effect on growth/reproduction (primed)</td>
</tr>
<tr class="even">
<td><strong>Fidalgo Bay</strong></td>
<td>Fastest</td>
<td>Moderate (low in warm sites)</td>
<td>Fewest larvae; delayed, variable onset</td>
<td>Moderate response; minor effects</td>
</tr>
<tr class="odd">
<td><strong>Oyster Bay</strong></td>
<td>Moderate</td>
<td>Lowest</td>
<td>Highest fecundity; earliest spawning (~10 d)</td>
<td>No transcriptomic response; only population with growth/reproduction harmed; larger larvae</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="physiological-and-molecular-divergence-population-specific-stress-response" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Physiological and Molecular Divergence: Population-Specific Stress Response</h1>
<section id="gene-expression-under-acute-stress-heare-2018" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="gene-expression-under-acute-stress-heare-2018"><span class="header-section-number">5.1</span> Gene expression under acute stress (Heare 2018)</h2>
<p>Having established phenotypic differences, <span class="citation" data-cites="heare2018">Heare et al. (<a href="#ref-heare2018" role="doc-biblioref">2018</a>)</span> asked whether they have molecular underpinnings. Oysters from the three bays were exposed to heat and mechanical stress and assayed for expression of growth, immune, and gene-regulatory genes. Heat stress altered molecular-regulatory genes; mechanical stress altered immune genes; and—mirroring the phenotypic data—Oyster Bay oysters mounted the most dramatic transcriptional response. These results gave the first mechanistic clue that the population physiotypes are wired in at the level of gene regulation.</p>
</section>
<section id="population-specific-response-to-ocean-acidification-spencer-2023" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="population-specific-response-to-ocean-acidification-spencer-2023"><span class="header-section-number">5.2</span> Population-specific response to ocean acidification (Spencer 2023)</h2>
<p>The most complete physiological test comes from <span class="citation" data-cites="spencer2023">Spencer, Roberts, and Silliman (<a href="#ref-spencer2023" role="doc-biblioref">2023</a>)</span>, which leveraged oysters from the same three populations bred and reared in common conditions for <strong>four years</strong> before exposing them to elevated pCO2. The populations responded as fundamentally different physiotypes, and—remarkably—the response pattern tracked the growth/survival/fecundity trade-off identified years earlier:</p>
<ul>
<li><strong>Dabob Bay</strong> (slow growth, high survival) mounted the largest transcriptional response—132 differentially expressed genes—yet showed no detectable cost to growth or reproduction. It constitutively expressed a distinct suite of antibacterial, antiviral, metabolic, growth, and reproductive genes, suggesting it is physiologically primed and stress-tolerant.</li>
<li><strong>Fidalgo Bay</strong> (fast growth) showed a moderate response (76 DEGs) with only minor effects on sex ratio and none on growth.</li>
<li><strong>Oyster Bay</strong> (high fecundity, low survival) did not respond at the transcript level at all, and was the only population whose growth and reproductive development were negatively affected by acidification—though its larvae were larger, which could partly buffer offspring in the wild.</li>
</ul>
<p>This is a textbook illustration of why populations are not interchangeable under climate stress: the same stressor produces opposite outcomes depending on source population, and the most stress-tolerant population (Dabob) is also the slowest-growing—exactly the animals a yield-focused program might be tempted to discard.</p>
</section>
<section id="reproductive-phenology-and-intergenerational-carryover-spencer-2020-2021" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="reproductive-phenology-and-intergenerational-carryover-spencer-2020-2021"><span class="header-section-number">5.3</span> Reproductive phenology and intergenerational carryover (Spencer 2020, 2021)</h2>
<p>Two further studies examined how the environment—particularly warming winters—interacts with reproduction. <span class="citation" data-cites="spencer2020">Spencer et al. (<a href="#ref-spencer2020" role="doc-biblioref">2020</a>)</span> sequentially exposed adults to elevated winter temperature and then elevated pCO2. Winter warming <strong>accelerated spermatogenesis</strong>, causing earlier and more abundant larval release, while high pCO2 negated that acceleration—so the two stressors can mask one another. Critically, offspring of parents exposed to elevated pCO2 had higher survival in two of four outplant bays: an <strong>intergenerational carryover effect</strong> demonstrating that parental conditioning, not just genotype, shapes offspring performance, and that pre-conditioning in stressful conditions can make <em>O. lurida</em> more resilient in certain environments.</p>
<p><span class="citation" data-cites="spencer2021">Spencer et al. (<a href="#ref-spencer2021" role="doc-biblioref">2021</a>)</span> refined the picture by adding food availability. Elevated winter temperature (10 °C vs.&nbsp;7 °C) produced larger, more developed gametes and larger larvae—especially with abundant food—implying low-level gametogenesis continues through winter, below the long-assumed ~12.5 °C threshold. But winter temperature did not affect larval survival or the timing/magnitude of larval production. The conclusion: <em>O. lurida</em> reproduction is <strong>largely resilient to winter warming</strong>, and in the hatchery, larval output is not contingent on winter conditions. Together these studies show reproductive phenology is environmentally tunable yet buffered—important context for predicting how wild recruitment will shift under climate change.</p>
</section>
<section id="early-life-history-and-recruitment-supply-becker-2020" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="early-life-history-and-recruitment-supply-becker-2020"><span class="header-section-number">5.4</span> Early life history and recruitment supply (Becker 2020)</h2>
<p>Population persistence ultimately depends on local recruitment. <span class="citation" data-cites="becker2020">Becker et al. (<a href="#ref-becker2020" role="doc-biblioref">2020</a>)</span> mapped brooders, planktonic larvae, and settlers weekly through a spawning season at the Fidalgo Bay restoration site. Brooding peaked in early July (never exceeding ~13% of adults), larvae peaked in mid-July, and settlement was strongly patchy—higher near conspecific adults and near a trestle bridge that altered hydrodynamics, and concentrated at an intermediate intertidal band (~ −0.3 m MLLW) where flow was favorable. Temperature was the dominant driver. The practical lesson is that pre-recruitment processes—larval supply, transport, and settlement microhabitat—govern where oysters establish, so restoration succeeds best when appropriate substrate is added near existing conspecifics and just below mean lower low water.</p>
</section>
</section>
<section id="epigenetic-divergence-methylation-coupled-to-genotype" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Epigenetic Divergence: Methylation Coupled to Genotype</h1>
<p>The deepest layer of differentiation comes from <span class="citation" data-cites="silliman2023">K. Silliman et al. (<a href="#ref-silliman2023" role="doc-biblioref">2023</a>)</span>, the first genome-wide characterization of DNA methylation in the genus <em>Ostrea</em>. Integrating genomic and methylation data for two populations under controlled within-generation conditions, the study identified <strong>3,963 differentially methylated loci between populations</strong> and showed that genetic and epigenetic variation are coupled: roughly <strong>27% of among-individual methylation variation is explained by genotype</strong>, through both CpG-creating/destroying SNPs and more distant methylation quantitative trait loci (mQTLs).</p>
<p>Two nuances matter for interpretation. First, the genetic–epigenetic coupling that is clear genome-wide breaks down when divergence is compared region by region—a caution for the methods commonly used to infer epigenetic–genetic links in marine invertebrates. Second, a substantial fraction of methylation variation is not attributable to genotype or to developmental environment, pointing to additional molecular mechanisms that could produce long-term, potentially heritable shifts in phenotype. This positions methylation as both a partial readout of genetic differentiation and an independent axis of population variation—another reason genetically distinct populations are unlikely to be functionally interchangeable.</p>
</section>
<section id="integration-a-coherent-picture-of-population-differentiation" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Integration: A Coherent Picture of Population Differentiation</h1>
<p>Read together, the eleven studies tell a single, internally consistent story across levels of biological organization:</p>
<ol type="1">
<li><strong>Genotype.</strong> <em>O. lurida</em> is regionally structured rangewide (six phylogeographic regions shaped by isolation-by-distance and biogeographic barriers) and finely structured locally, with the brooding life history limiting effective dispersal.</li>
<li><strong>Phenotype.</strong> Local populations express heritable trade-offs—Dabob (survival), Fidalgo (growth), Oyster Bay (fecundity)—that persist across two generations and multiple independent experiments.</li>
<li><strong>Physiology.</strong> Those phenotypes have molecular signatures: population-specific transcriptional responses to heat, mechanical stress, and acidification, with stress tolerance and growth rate inversely related.</li>
<li><strong>Epigenome.</strong> Methylation differs between populations and is partly coupled to genotype, adding a further heritable axis of divergence.</li>
<li><strong>Recruitment.</strong> Local environmental and hydrodynamic processes govern larval supply and settlement, so differentiation is continually reinforced by limited, patchy recruitment.</li>
</ol>
<p>The unifying theme is a <strong>growth–survival–reproduction–stress-tolerance trade-off</strong> that is genetically and epigenetically encoded, environmentally tunable, and ecologically consequential. No single population is best; each represents a different solution to its local estuarine environment, and that diversity is itself the resource worth conserving.</p>
</section>
<section id="implications-for-restoration-and-aquaculture-practice" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Implications for Restoration and Aquaculture Practice</h1>
<p>The convergent finding that Olympia oyster populations are genetically, phenotypically, physiologically, and epigenetically distinct—and that these differences are heritable and adaptive—has direct, actionable consequences for how restoration and aquaculture should be conducted.</p>
<section id="treat-populations-as-locally-adapted-management-units" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="treat-populations-as-locally-adapted-management-units"><span class="header-section-number">8.1</span> Treat populations as locally adapted management units</h2>
<p>Because differences persist across generations and common environments, populations should be managed as distinct units rather than as a single interchangeable stock. Rangewide, the six phylogeographic regions provide a natural framework for management boundaries; within regions, even bays tens of kilometers apart (Dabob, Oyster, Fidalgo) are demonstrably different. Outplanting decisions should respect these boundaries unless there is an explicit, evidence-based reason to do otherwise.</p>
</section>
<section id="source-broodstock-locally-and-avoid-homogenizing-transfers" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="source-broodstock-locally-and-avoid-homogenizing-transfers"><span class="header-section-number">8.2</span> Source broodstock locally and avoid homogenizing transfers</h2>
<p>Inadvertent transfer of stocks among regions or bays can swamp local adaptation with maladapted alleles and erase the structure that confers resilience. Restoration programs should prioritize local broodstock for local outplanting, document provenance, and avoid moving animals across biogeographic barriers (Cape Mendocino, Monterey Bay, Cape Flattery) or between distinct Puget Sound basins without justification.</p>
</section>
<section id="protect-genetic-diversity-in-the-hatchery" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="protect-genetic-diversity-in-the-hatchery"><span class="header-section-number">8.3</span> Protect genetic diversity in the hatchery</h2>
<p>Hatchery practice that uses few broodstock to produce many outplants reduces effective population size and genetic diversity precisely where restoration aims to build resilience. Programs should use large, representative broodstock panels, spawn many family groups, equalize family contributions where possible, and monitor effective population size and diversity (the existing GBS/SNP panels and outlier loci are well suited to this). The goal is to add genetic resilience, not just census numbers.</p>
</section>
<section id="match-source-population-to-restoration-goal-and-future-climate" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="match-source-population-to-restoration-goal-and-future-climate"><span class="header-section-number">8.4</span> Match source population to restoration goal and future climate</h2>
<p>The trade-offs mean there is no universally optimal stock—source choice should follow the objective and the projected environment:</p>
<ul>
<li><strong>For survival and persistence under stress / acidification:</strong> Dabob-type populations (slow growth, high survival, strong primed molecular stress response) are advantageous, especially in corrosive or variable habitats.</li>
<li><strong>For rapid biomass and reef-building:</strong> Fidalgo-type populations (fast growth) may establish structure faster, but with weaker survival in warm sites and lower reproductive output.</li>
<li><strong>For reproductive output and self-recruitment:</strong> Oyster Bay–type populations (high fecundity, early spawning) maximize larval supply, but are the most vulnerable to acidification and have lower adult survival.</li>
</ul>
<p>Critically, a yield- or growth-focused selection program would tend to favor fast-growing stock and discard the slow-growing Dabob-type animals that are in fact the most stress-tolerant—an outcome that would reduce climate resilience. Selection criteria should therefore weight survival and stress tolerance, not growth alone.</p>
</section>
<section id="leverage-parental-conditioning-carryover-effects" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="leverage-parental-conditioning-carryover-effects"><span class="header-section-number">8.5</span> Leverage parental conditioning (carryover effects)</h2>
<p>Because parental exposure to stressors can improve offspring survival in some environments, hatcheries may be able to use deliberate broodstock conditioning to pre-adapt outplants to target sites. This is a promising but still preliminary lever; effects are environment-dependent and should be validated per site before operational use.</p>
</section>
<section id="optimize-outplant-siting-and-timing" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="optimize-outplant-siting-and-timing"><span class="header-section-number">8.6</span> Optimize outplant siting and timing</h2>
<p>Field recruitment data indicate restoration is improved by adding suitable substrate near existing conspecifics and at intermediate intertidal elevations (~ −0.3 m MLLW) where flow favors settlement. Because reproductive phenology shifts with temperature (earlier, larger gametes after warmer winters) but larval survival is buffered, managers can anticipate earlier recruitment in warm years without expecting catastrophic phenological failure—while still monitoring for acidification, which can mask warming’s effects and harm sensitive populations such as Oyster Bay.</p>
</section>
</section>
<section id="next-steps-in-research" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Next Steps in Research</h1>
<p>The synthesized work resolves that populations differ and largely why it matters, but it also defines a clear research agenda. Priorities follow directly from the gaps and open questions in the collection.</p>
<section id="link-adaptive-genotype-to-phenotype" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="link-adaptive-genotype-to-phenotype"><span class="header-section-number">9.1</span> Link adaptive genotype to phenotype</h2>
<p>The outlier loci identified rangewide (developmental, sensory, metabolic, immune, and muscle genes) are candidates, not confirmed adaptive variants. Functional validation—associating specific alleles or methylation states with growth, survival, fecundity, and acidification tolerance—would convert candidate markers into usable selection and monitoring tools.</p>
</section>
<section id="disentangle-genetic-epigenetic-and-carryover-contributions" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="disentangle-genetic-epigenetic-and-carryover-contributions"><span class="header-section-number">9.2</span> Disentangle genetic, epigenetic, and carryover contributions</h2>
<p>Methylation is partly coupled to genotype but partly independent, and carryover effects are heritable yet environment-dependent. Multigenerational designs that simultaneously track genotype, methylome, and parental environment are needed to quantify how much of the population physiotype is hard-wired versus tunable—and how durable epigenetic shifts are across generations.</p>
</section>
<section id="extend-physiological-testing-across-the-full-range-and-multiple-stressors" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="extend-physiological-testing-across-the-full-range-and-multiple-stressors"><span class="header-section-number">9.3</span> Extend physiological testing across the full range and multiple stressors</h2>
<p>Population-specific stress responses are documented chiefly for three Puget Sound bays. Comparable acidification, warming, hypoxia, and salinity experiments across the six phylogeographic regions would reveal whether the growth–survival–tolerance trade-off generalizes, and would identify which regional stocks harbor the most valuable adaptive variation for a changing ocean.</p>
</section>
<section id="quantify-real-world-larval-dispersal-and-connectivity" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="quantify-real-world-larval-dispersal-and-connectivity"><span class="header-section-number">9.4</span> Quantify real-world larval dispersal and connectivity</h2>
<p>The brooding life history predicts limited dispersal, but effective connectivity—how far larvae actually move and recruit—remains poorly quantified. Coupling genomic parentage/assignment with biophysical transport models and field recruitment surveys (building on the Becker framework) would define management-unit boundaries empirically and inform restoration network design.</p>
</section>
<section id="build-a-genomic-monitoring-and-broodstock-management-toolkit" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="build-a-genomic-monitoring-and-broodstock-management-toolkit"><span class="header-section-number">9.5</span> Build a genomic monitoring and broodstock-management toolkit</h2>
<p>The existing SNP panels, transcriptomes, and methylation data should be consolidated into a standardized, low-cost genotyping panel for tracking effective population size, diversity, provenance, and adaptive loci in restored and hatchery populations—closing the loop between research findings and operational stock management.</p>
</section>
<section id="test-conditioning-and-assisted-adaptation-strategies-operationally" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="test-conditioning-and-assisted-adaptation-strategies-operationally"><span class="header-section-number">9.6</span> Test conditioning and assisted-adaptation strategies operationally</h2>
<p>Given preliminary evidence for beneficial carryover effects, controlled trials of broodstock pre-conditioning and site-matched outplanting—paired with long-term survival monitoring—would establish whether assisted adaptation can be deployed at restoration scale without compromising genetic diversity.</p>
</section>
</section>
<section id="conclusion" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Conclusion</h1>
<p>Across genomes, phenotypes, physiology, and epigenomes, the evidence is unambiguous: Olympia oyster populations are fundamentally and heritably different from one another, at scales ranging from the entire west coast down to neighboring Puget Sound bays. These differences are not noise to be averaged away in restoration—they are adaptive variation that determines how populations grow, survive, reproduce, and withstand a changing ocean. The central recommendation that follows is equally clear: <strong>conserve population structure.</strong> Source locally, protect genetic diversity through hatchery practice, match stock to goal and future climate, and treat the diversity among populations as the foundational resource that makes long-term Olympia oyster recovery possible.</p>
<section id="suggested-citation" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="suggested-citation"><span class="header-section-number">10.1</span> Suggested citation</h2>
<p>Roberts, S. B. 2026. <em>Fundamental Differences Among Olympia Oyster Populations: An Integrated Synthesis of Genetic, Phenotypic, Physiological, and Epigenetic Divergence in Ostrea lurida</em>. Current Findings. Available at: https://robertslab.github.io/current-findings/reports/olympia-oyster-population-synthesis/</p>
</section>
<section id="version-history" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="version-history"><span class="header-section-number">10.2</span> Version history</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Version</th>
<th>Date</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.1</td>
<td>2026-06-17</td>
<td>Migrated from Oly_population_synthesis.docx</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-becker2020" class="csl-entry" role="listitem">
Becker, Bonnie J., Michael D. Behrens, Brian Allen, Megan Hintz, Hannah Parker, Michelle M. McCartha, and Sarah M. White. 2020. <span>“Spatial and Temporal Distribution of the Early Life History Stages of the Native Olympia Oyster <span>Ostrea</span> Lurida (<span>Carpenter</span>, 1864) in a Restoration Site in Northern <span>Puget</span> <span>Sound</span>, <span>WA</span>.”</span> <em>Journal of Shellfish Research</em> 39 (1): 43–58. <a href="https://doi.org/10.2983/035.039.0105">https://doi.org/10.2983/035.039.0105</a>.
</div>
<div id="ref-heare2017" class="csl-entry" role="listitem">
Heare, Jacob E., Brady Blake, Jonathan P. Davis, Brent Vadopalas, and Steven B. Roberts. 2017. <span>“Evidence of <span>Ostrea</span> Lurida <span>Carpenter</span> 1864 Population Structure in <span>Puget</span> <span>Sound</span>, <span>WA</span>, <span>USA</span>.”</span> <em>Marine Ecology</em> 38 (5): e12458. <a href="https://doi.org/10.1111/maec.12458">https://doi.org/10.1111/maec.12458</a>.
</div>
<div id="ref-heare2018" class="csl-entry" role="listitem">
Heare, Jacob E., Samuel J. White, Brent Vadopalas, and Steven B. Roberts. 2018. <span>“Differential Response to Stress in <span>Ostrea</span> Lurida as Measured by Gene Expression.”</span> <em>PeerJ</em> 6: e4261. <a href="https://doi.org/10.7717/peerj.4261">https://doi.org/10.7717/peerj.4261</a>.
</div>
<div id="ref-silliman2019" class="csl-entry" role="listitem">
Silliman, Katherine. 2019. <span>“Population Structure, Genetic Connectivity, and Adaptation in the Olympia Oyster (<span>Ostrea</span> Lurida) Along the West Coast of <span>North</span> <span>America</span>.”</span> <em>Evolutionary Applications</em> 12 (5): 923–39. <a href="https://doi.org/10.1111/eva.12766">https://doi.org/10.1111/eva.12766</a>.
</div>
<div id="ref-silliman2018" class="csl-entry" role="listitem">
Silliman, Katherine E., Tynan K. Bowyer, and Steven B. Roberts. 2018. <span>“Consistent Differences in Fitness Traits Across Multiple Generations of Olympia Oysters.”</span> <em>Scientific Reports</em> 8 (1): 6080. <a href="https://doi.org/10.1038/s41598-018-24455-3">https://doi.org/10.1038/s41598-018-24455-3</a>.
</div>
<div id="ref-silliman2023" class="csl-entry" role="listitem">
Silliman, Katherine, Laura H. Spencer, Samuel J. White, and Steven B. Roberts. 2023. <span>“Epigenetic and Genetic Population Structure Is Coupled in a Marine Invertebrate.”</span> <em>Genome Biology and Evolution</em> 15 (2): evad013. <a href="https://doi.org/10.1093/gbe/evad013">https://doi.org/10.1093/gbe/evad013</a>.
</div>
<div id="ref-spencer2021" class="csl-entry" role="listitem">
Spencer, Laura H., Erin Horkan, Ryan Crim, and Steven B. Roberts. 2021. <span>“Latent Effects of Winter Warming on Olympia Oyster Reproduction and Larval Viability.”</span> <em>Journal of Experimental Marine Biology and Ecology</em> 542–543: 151604. <a href="https://doi.org/10.1016/j.jembe.2021.151604">https://doi.org/10.1016/j.jembe.2021.151604</a>.
</div>
<div id="ref-spencer2023" class="csl-entry" role="listitem">
Spencer, Laura H., Steven B. Roberts, and Katherine Silliman. 2023. <span>“Population-Specific Effects of Ocean Acidification in the Olympia Oyster.”</span> <em>bioRxiv</em>. <a href="https://doi.org/10.1101/2023.09.08.556443">https://doi.org/10.1101/2023.09.08.556443</a>.
</div>
<div id="ref-spencer2020" class="csl-entry" role="listitem">
Spencer, Laura H., Yaamini R. Venkataraman, Ryan Crim, Stuart Ryan, Micah J. Horwith, and Steven B. Roberts. 2020. <span>“Carryover Effects of Temperature and <span class="nocase">pCO2</span> Across Multiple Olympia Oyster Populations.”</span> <em>Ecological Applications</em> 30 (3): e02060. <a href="https://doi.org/10.1002/eap.2060">https://doi.org/10.1002/eap.2060</a>.
</div>
<div id="ref-timminsschiffman2013" class="csl-entry" role="listitem">
Timmins-Schiffman, Emma B., Carolyn S. Friedman, Dave C. Metzger, Samuel J. White, and Steven B. Roberts. 2013. <span>“Genomic Resource Development for Shellfish of Conservation Concern.”</span> <em>Molecular Ecology Resources</em> 13 (2): 295–305. <a href="https://doi.org/10.1111/1755-0998.12052">https://doi.org/10.1111/1755-0998.12052</a>.
</div>
<div id="ref-white2017" class="csl-entry" role="listitem">
White, Samuel J., Brent Vadopalas, Katherine Silliman, and Steven B. Roberts. 2017. <span>“Genotype-by-Sequencing of Three Geographically Distinct Populations of Olympia Oysters, <span>Ostrea</span> Lurida.”</span> <em>Scientific Data</em> 4: 170130. <a href="https://doi.org/10.1038/sdata.2017.130">https://doi.org/10.1038/sdata.2017.130</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/robertslab\.github\.io\/current-findings\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Roberts Lab</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Not peer reviewed unless explicitly stated.</p>
</div>
  </div>
</footer>




</body></html>